/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package tools.vitruvius.dsls.mirbase.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MirBaseUiModule extends AbstractMirBaseUiModule {
}
