package edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation

import org.junit.runner.RunWith
import org.junit.runners.Suite
import org.junit.runners.Suite.SuiteClasses
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.BasicComponentMappingGplTransformationTests
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.CollectionDataTypeMappingGplTransformationTest
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.CompositeComponentMappingGplTransformationTest
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.CompositeDataTypeMappingGplTransformationTest
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.InnerDeclarationMappingGplTransformationTest
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.OperationInterfaceMappingGplTransformationTest
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.OperationProvidedRoleMappingGplTransformationTest
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.OperationRequiredRoleMappingGplTransformationTest
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.OperationSignatureMappingGplTransformationTest
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.PcmParameterMappingGplTransformationTest
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.RepositoryMappingGplTransformationTest
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.ResourceDemandingInternalBehaviorMappingGplTransformationTest
import edu.kit.ipd.sdq.vitruvius.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository.SeffMappingGplTransformationTest

@RunWith(Suite)
@SuiteClasses(BasicComponentMappingGplTransformationTests,
	CollectionDataTypeMappingGplTransformationTest,
	CompositeComponentMappingGplTransformationTest,
	CompositeDataTypeMappingGplTransformationTest,
	InnerDeclarationMappingGplTransformationTest,
	OperationInterfaceMappingGplTransformationTest,
	OperationProvidedRoleMappingGplTransformationTest,
	OperationRequiredRoleMappingGplTransformationTest,
	OperationSignatureMappingGplTransformationTest,
	PcmParameterMappingGplTransformationTest,
	RepositoryMappingGplTransformationTest,
	ResourceDemandingInternalBehaviorMappingGplTransformationTest,
	SeffMappingGplTransformationTest)
class Pcm2JavaRepositoryGplTestSuite {
}
