/*
 * generated by Xtext 2.10.0
 */
package tools.vitruvius.dsls.response.parser.antlr;

import com.google.inject.Inject;
import tools.vitruvius.dsls.response.parser.antlr.internal.InternalResponseLanguageParser;
import tools.vitruvius.dsls.response.services.ResponseLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ResponseLanguageParser extends AbstractAntlrParser {

	@Inject
	private ResponseLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalResponseLanguageParser createParser(XtextTokenStream stream) {
		return new InternalResponseLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ResponseFile";
	}

	public ResponseLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ResponseLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
