package edu.kit.ipd.sdq.vitruvius.framework.contracts.internal;

enum BlackboardState {

    WAITING4CHANGES, WAITING4TRANSFORMATION, WAITING4COMMANDS, WAITING4EXECUTION, WAITING4CHECK, WAITING4UNDO, WAITING4REDO
}
