/**
 * generated by Xtext 2.10.0
 */
package edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Remove Root Change</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage#getRemoveRootChange()
 * @model
 * @generated
 */
public interface RemoveRootChange extends AtomicRootObjectChange
{
} // RemoveRootChange
