/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Valued Feature Create</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage#getSingleValuedFeatureCreate()
 * @model
 * @generated
 */
public interface SingleValuedFeatureCreate extends AtomicSingleValuedFeatureChange
{
} // SingleValuedFeatureCreate
