/**
 *
 * $Id$
 */
package tools.vitruv.framework.change.echange.eobject.validation;

import org.eclipse.emf.ecore.EObject;

import tools.vitruv.framework.change.echange.resolve.StagingArea;

/**
 * A sample validator interface for {@link tools.vitruv.framework.change.echange.eobject.EObjectExistenceEChange}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EObjectExistenceEChangeValidator {
	boolean validate();

	boolean validateAffectedEObject(EObject value);
	boolean validateStagingArea(StagingArea value);
}
