package tools.vitruv.applications.demo.insurancepersons.insurance2persons

class InsuranceToPersonsChangePropagationSpecification extends mir.reactions.insuranceToPersons.InsuranceToPersonsChangePropagationSpecification {
}
