<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="change" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/1.0"
    nsPrefix="change">
  <eClassifiers xsi:type="ecore:EClass" name="EChange" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getNewValue" lowerBound="1">
      <eGenericType eTypeParameter="#//AdditiveChange/T"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubtractiveChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getOldValue" lowerBound="1">
      <eGenericType eTypeParameter="#//SubtractiveChange/T"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplaciveChange">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//SubtractiveChange">
      <eTypeArguments eTypeParameter="#//ReplaciveChange/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//AdditiveChange">
      <eTypeArguments eTypeParameter="#//ReplaciveChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveAttributeChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" lowerBound="1">
      <eGenericType eTypeParameter="#//AdditiveAttributeChange/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//AdditiveChange">
      <eTypeArguments eTypeParameter="#//AdditiveAttributeChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubtractiveAttributeChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldValue" lowerBound="1">
      <eGenericType eTypeParameter="#//SubtractiveAttributeChange/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//SubtractiveChange">
      <eTypeArguments eTypeParameter="#//SubtractiveAttributeChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplaciveAttributeChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//SubtractiveAttributeChange">
      <eTypeArguments eTypeParameter="#//ReplaciveAttributeChange/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//AdditiveAttributeChange">
      <eTypeArguments eTypeParameter="#//ReplaciveAttributeChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveReferenceChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValue" lowerBound="1">
      <eGenericType eTypeParameter="#//AdditiveReferenceChange/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//AdditiveChange">
      <eTypeArguments eTypeParameter="#//AdditiveReferenceChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubtractiveReferenceChange" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldTUID" lowerBound="1"
        eType="#//TUID"/>
    <eGenericSuperTypes eClassifier="#//SubtractiveChange">
      <eTypeArguments eClassifier="#//TUID"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplaciveReferenceChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//SubtractiveReferenceChange"/>
    <eGenericSuperTypes eClassifier="#//AdditiveReferenceChange">
      <eTypeArguments eTypeParameter="#//ReplaciveReferenceChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TUID" instanceClassName="edu.kit.ipd.sdq.vitruvius.framework.contracts.datatypes.TUID"/>
  <eSubpackages name="feature" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Feature/1.0"
      nsPrefix="feature">
    <eClassifiers xsi:type="ecore:EClass" name="EFeatureChange" abstract="true" eSuperTypes="#//EChange">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="affectedFeature" lowerBound="1">
        <eGenericType eTypeParameter="#//feature/EFeatureChange/T"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="oldAffectedEObject" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="newAffectedEObject" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UpdateEFeature" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eTypeParameters>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UpdateMultiValuedEFeature" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//feature/UpdateEFeature">
        <eTypeArguments eTypeParameter="#//feature/UpdateMultiValuedEFeature/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UpdateSingleValuedEFeature" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//feature/UpdateEFeature">
        <eTypeArguments eTypeParameter="#//feature/UpdateSingleValuedEFeature/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnsetEFeature" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//feature/EFeatureChange">
        <eTypeArguments eTypeParameter="#//feature/UnsetEFeature/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnsetEAttribute">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//feature/UnsetEFeature">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="#//SubtractiveAttributeChange">
        <eTypeArguments eTypeParameter="#//feature/UnsetEAttribute/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnsetEReference">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eOperations name="isContainment" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eGenericSuperTypes eClassifier="#//feature/UnsetEFeature">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="#//SubtractiveReferenceChange"/>
    </eClassifiers>
    <eSubpackages name="list" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Feature/List/1.0"
        nsPrefix="list">
      <eClassifiers xsi:type="ecore:EClass" name="UpdateSingleEListEntry" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
        <eGenericSuperTypes eClassifier="#//feature/UpdateMultiValuedEFeature">
          <eTypeArguments eTypeParameter="#//feature/list/UpdateSingleEListEntry/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InsertInEList" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/UpdateSingleEListEntry">
          <eTypeArguments eTypeParameter="#//feature/list/InsertInEList/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//AdditiveChange">
          <eTypeArguments eTypeParameter="#//feature/list/InsertInEList/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RemoveFromEList" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="removedObjectURIFragment"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral="0"/>
        <eGenericSuperTypes eClassifier="#//feature/list/UpdateSingleEListEntry">
          <eTypeArguments eTypeParameter="#//feature/list/RemoveFromEList/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//SubtractiveChange">
          <eTypeArguments eTypeParameter="#//feature/list/RemoveFromEList/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceInEList" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/InsertInEList">
          <eTypeArguments eTypeParameter="#//feature/list/ReplaceInEList/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/list/RemoveFromEList">
          <eTypeArguments eTypeParameter="#//feature/list/ReplaceInEList/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PermuteEList" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="newIndexForElementAt"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eGenericSuperTypes eClassifier="#//feature/UpdateMultiValuedEFeature">
          <eTypeArguments eTypeParameter="#//feature/list/PermuteEList/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="attribute" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Feature/Attribute/1.0"
        nsPrefix="attribute">
      <eClassifiers xsi:type="ecore:EClass" name="UpdateEAttribute" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/EFeatureChange">
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceSingleValuedEAttribute">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/UpdateSingleValuedEFeature">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//ReplaciveAttributeChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InsertEAttributeValue">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/InsertInEList">
          <eTypeArguments eTypeParameter="#//feature/attribute/InsertEAttributeValue/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/InsertEAttributeValue/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RemoveEAttributeValue">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/RemoveFromEList">
          <eTypeArguments eTypeParameter="#//feature/attribute/RemoveEAttributeValue/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/RemoveEAttributeValue/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceEAttributeValue">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/ReplaceInEList">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceEAttributeValue/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceEAttributeValue/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PermuteEAttributeValues">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/PermuteEList">
          <eTypeArguments eTypeParameter="#//feature/attribute/PermuteEAttributeValues/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/PermuteEAttributeValues/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="reference" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Feature/Reference/Containment/1.0"
        nsPrefix="reference">
      <eClassifiers xsi:type="ecore:EClass" name="UpdateEReference" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/EFeatureChange">
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UpdateNonContainmentEReference"
          abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/UpdateNonContainmentEReference/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UpdateSingleValuedNonContainmentEReference">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldValue" lowerBound="1">
          <eGenericType eTypeParameter="#//feature/reference/UpdateSingleValuedNonContainmentEReference/T"/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" lowerBound="1">
          <eGenericType eTypeParameter="#//feature/reference/UpdateSingleValuedNonContainmentEReference/T"/>
        </eStructuralFeatures>
        <eGenericSuperTypes eClassifier="#//feature/UpdateSingleValuedEFeature">
          <eTypeArguments eTypeParameter="#//feature/reference/UpdateSingleValuedNonContainmentEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateNonContainmentEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/UpdateSingleValuedNonContainmentEReference/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InsertNonContainmentEReference">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/InsertInEList">
          <eTypeArguments eTypeParameter="#//feature/reference/InsertNonContainmentEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateNonContainmentEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/InsertNonContainmentEReference/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceNonContainmentEReference">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/ReplaceInEList">
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceNonContainmentEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateNonContainmentEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceNonContainmentEReference/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RemoveNonContainmentEReference">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/RemoveFromEList">
          <eTypeArguments eTypeParameter="#//feature/reference/RemoveNonContainmentEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateNonContainmentEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/RemoveNonContainmentEReference/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PermuteNonContainmentEReferenceValues">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/PermuteEList">
          <eTypeArguments eTypeParameter="#//feature/reference/PermuteNonContainmentEReferenceValues/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateNonContainmentEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/PermuteNonContainmentEReferenceValues/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eSubpackages name="containment" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Reference/Containment/1.0"
          nsPrefix="containment">
        <eClassifiers xsi:type="ecore:EClass" name="UpdateContainmentEReference" abstract="true">
          <eTypeParameters name="T">
            <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          </eTypeParameters>
          <eGenericSuperTypes eClassifier="#//feature/reference/UpdateEReference">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/UpdateContainmentEReference/T"/>
          </eGenericSuperTypes>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="UpdateSingleValuedContainmentEReference"
            abstract="true">
          <eTypeParameters name="T">
            <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          </eTypeParameters>
          <eGenericSuperTypes eClassifier="#//feature/UpdateSingleValuedEFeature">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/UpdateSingleValuedContainmentEReference/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/reference/containment/UpdateContainmentEReference">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/UpdateSingleValuedContainmentEReference/T"/>
          </eGenericSuperTypes>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="CreateNonRootEObjectSingle">
          <eTypeParameters name="T">
            <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          </eTypeParameters>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" lowerBound="1">
            <eGenericType eTypeParameter="#//feature/reference/containment/CreateNonRootEObjectSingle/T"/>
          </eStructuralFeatures>
          <eGenericSuperTypes eClassifier="#//object/CreateEObject">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/CreateNonRootEObjectSingle/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/reference/containment/UpdateSingleValuedContainmentEReference">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/CreateNonRootEObjectSingle/T"/>
          </eGenericSuperTypes>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ReplaceNonRootEObjectSingle">
          <eTypeParameters name="T">
            <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          </eTypeParameters>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldValue" lowerBound="1">
            <eGenericType eTypeParameter="#//feature/reference/containment/ReplaceNonRootEObjectSingle/T"/>
          </eStructuralFeatures>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" lowerBound="1">
            <eGenericType eTypeParameter="#//feature/reference/containment/ReplaceNonRootEObjectSingle/T"/>
          </eStructuralFeatures>
          <eGenericSuperTypes eClassifier="#//object/ReplaceEObject">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/ReplaceNonRootEObjectSingle/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/reference/containment/UpdateSingleValuedContainmentEReference">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/ReplaceNonRootEObjectSingle/T"/>
          </eGenericSuperTypes>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DeleteNonRootEObjectSingle">
          <eTypeParameters name="T">
            <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          </eTypeParameters>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldValue" lowerBound="1">
            <eGenericType eTypeParameter="#//feature/reference/containment/DeleteNonRootEObjectSingle/T"/>
          </eStructuralFeatures>
          <eGenericSuperTypes eClassifier="#//object/DeleteEObject">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/DeleteNonRootEObjectSingle/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/reference/containment/UpdateSingleValuedContainmentEReference">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/DeleteNonRootEObjectSingle/T"/>
          </eGenericSuperTypes>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="CreateNonRootEObjectInList">
          <eTypeParameters name="T">
            <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          </eTypeParameters>
          <eGenericSuperTypes eClassifier="#//object/CreateEObject">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/CreateNonRootEObjectInList/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/list/InsertInEList">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/CreateNonRootEObjectInList/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/reference/containment/UpdateContainmentEReference">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/CreateNonRootEObjectInList/T"/>
          </eGenericSuperTypes>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ReplaceNonRootEObjectInList">
          <eTypeParameters name="T">
            <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          </eTypeParameters>
          <eGenericSuperTypes eClassifier="#//object/ReplaceEObject">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/ReplaceNonRootEObjectInList/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/list/ReplaceInEList">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/ReplaceNonRootEObjectInList/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/reference/containment/UpdateContainmentEReference">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/ReplaceNonRootEObjectInList/T"/>
          </eGenericSuperTypes>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DeleteNonRootEObjectInList">
          <eTypeParameters name="T">
            <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          </eTypeParameters>
          <eGenericSuperTypes eClassifier="#//object/DeleteEObject">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/DeleteNonRootEObjectInList/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/list/RemoveFromEList">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/DeleteNonRootEObjectInList/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/reference/containment/UpdateContainmentEReference">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/DeleteNonRootEObjectInList/T"/>
          </eGenericSuperTypes>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="PermuteContainmentEReferenceValues">
          <eTypeParameters name="T">
            <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          </eTypeParameters>
          <eGenericSuperTypes eClassifier="#//feature/list/PermuteEList">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/PermuteContainmentEReferenceValues/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/reference/containment/UpdateContainmentEReference">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/PermuteContainmentEReferenceValues/T"/>
          </eGenericSuperTypes>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="InsertNonRootEObjectInContainmentList">
          <eTypeParameters name="T">
            <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          </eTypeParameters>
          <eGenericSuperTypes eClassifier="#//feature/list/InsertInEList">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/InsertNonRootEObjectInContainmentList/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/reference/containment/UpdateContainmentEReference">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/InsertNonRootEObjectInContainmentList/T"/>
          </eGenericSuperTypes>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="RemoveNonRootEObjectFromContainmentList">
          <eTypeParameters name="T">
            <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
          </eTypeParameters>
          <eGenericSuperTypes eClassifier="#//feature/list/RemoveFromEList">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/RemoveNonRootEObjectFromContainmentList/T"/>
          </eGenericSuperTypes>
          <eGenericSuperTypes eClassifier="#//feature/reference/containment/UpdateContainmentEReference">
            <eTypeArguments eTypeParameter="#//feature/reference/containment/RemoveNonRootEObjectFromContainmentList/T"/>
          </eGenericSuperTypes>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="object" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Object/1.0"
      nsPrefix="object">
    <eClassifiers xsi:type="ecore:EClass" name="EObjectChange" abstract="true" eSuperTypes="#//EChange">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateEObject" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//object/EObjectChange">
        <eTypeArguments eTypeParameter="#//object/CreateEObject/T"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="#//AdditiveReferenceChange">
        <eTypeArguments eTypeParameter="#//object/CreateEObject/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReplaceEObject" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//object/EObjectChange">
        <eTypeArguments eTypeParameter="#//object/ReplaceEObject/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeleteEObject" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//object/EObjectChange">
        <eTypeArguments eTypeParameter="#//object/DeleteEObject/T"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="#//SubtractiveReferenceChange"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateRootEObject">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//object/CreateEObject">
        <eTypeArguments eTypeParameter="#//object/CreateRootEObject/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeleteRootEObject">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//object/DeleteEObject">
        <eTypeArguments eTypeParameter="#//object/DeleteRootEObject/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReplaceRootEObject">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//object/DeleteRootEObject">
        <eTypeArguments eTypeParameter="#//object/ReplaceRootEObject/T"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="#//object/CreateRootEObject">
        <eTypeArguments eTypeParameter="#//object/ReplaceRootEObject/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
