<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="change" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/1.0"
    nsPrefix="change">
  <eClassifiers xsi:type="ecore:EClass" name="EChange" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveChange" abstract="true" eSuperTypes="#//EChange">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getNewValue" lowerBound="1">
      <eGenericType eTypeParameter="#//AdditiveChange/T"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubtractiveChange" abstract="true" eSuperTypes="#//EChange">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getOldValue" lowerBound="1">
      <eGenericType eTypeParameter="#//SubtractiveChange/T"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplaciveChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//SubtractiveChange">
      <eTypeArguments eTypeParameter="#//ReplaciveChange/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//AdditiveChange">
      <eTypeArguments eTypeParameter="#//ReplaciveChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveAttributeChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" lowerBound="1">
      <eGenericType eTypeParameter="#//AdditiveAttributeChange/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//AdditiveChange">
      <eTypeArguments eTypeParameter="#//AdditiveAttributeChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubtractiveAttributeChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldValue" lowerBound="1">
      <eGenericType eTypeParameter="#//SubtractiveAttributeChange/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//SubtractiveChange">
      <eTypeArguments eTypeParameter="#//SubtractiveAttributeChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplaciveAttributeChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//SubtractiveAttributeChange">
      <eTypeArguments eTypeParameter="#//ReplaciveAttributeChange/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//AdditiveAttributeChange">
      <eTypeArguments eTypeParameter="#//ReplaciveAttributeChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveReferenceChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValue" lowerBound="1">
      <eGenericType eTypeParameter="#//AdditiveReferenceChange/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//AdditiveChange">
      <eTypeArguments eTypeParameter="#//AdditiveReferenceChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubtractiveReferenceChange" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldTUID" lowerBound="1"
        eType="#//TUID"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName2OldValueMap"
        lowerBound="1" transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//SubtractiveChange">
      <eTypeArguments eClassifier="#//TUID"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplaciveReferenceChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//SubtractiveReferenceChange"/>
    <eGenericSuperTypes eClassifier="#//AdditiveReferenceChange">
      <eTypeArguments eTypeParameter="#//ReplaciveReferenceChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TUID" instanceClassName="edu.kit.ipd.sdq.vitruvius.framework.contracts.datatypes.TUID"/>
  <eSubpackages name="feature" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Feature/1.0"
      nsPrefix="feature">
    <eClassifiers xsi:type="ecore:EClass" name="EFeatureChange" abstract="true" eSuperTypes="#//EChange">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="affectedFeature" lowerBound="1">
        <eGenericType eTypeParameter="#//feature/EFeatureChange/T"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="affectedEObject" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldTUIDOfAffectedEObject"
          lowerBound="1" eType="#//TUID"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UpdateEFeature" abstract="true" eSuperTypes="#//EChange">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eTypeParameters>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UpdateMultiValuedEFeature" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//feature/UpdateEFeature">
        <eTypeArguments eTypeParameter="#//feature/UpdateMultiValuedEFeature/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UpdateSingleValuedEFeature" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//feature/UpdateEFeature">
        <eTypeArguments eTypeParameter="#//feature/UpdateSingleValuedEFeature/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnsetEFeature" abstract="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//feature/EFeatureChange">
        <eTypeArguments eTypeParameter="#//feature/UnsetEFeature/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnsetEAttribute">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//feature/UnsetEFeature">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="#//SubtractiveAttributeChange">
        <eTypeArguments eTypeParameter="#//feature/UnsetEAttribute/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnsetEReference">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eOperations name="isContainment" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eGenericSuperTypes eClassifier="#//feature/UnsetEFeature">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="#//SubtractiveReferenceChange"/>
    </eClassifiers>
    <eSubpackages name="list" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Feature/List/1.0"
        nsPrefix="list">
      <eClassifiers xsi:type="ecore:EClass" name="UpdateSingleEListEntry" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
        <eGenericSuperTypes eClassifier="#//feature/UpdateMultiValuedEFeature">
          <eTypeArguments eTypeParameter="#//feature/list/UpdateSingleEListEntry/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InsertInEList" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/UpdateSingleEListEntry">
          <eTypeArguments eTypeParameter="#//feature/list/InsertInEList/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RemoveFromEList" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="removedObjectURIFragment"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral="0"/>
        <eGenericSuperTypes eClassifier="#//feature/list/UpdateSingleEListEntry">
          <eTypeArguments eTypeParameter="#//feature/list/RemoveFromEList/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PermuteEList" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="newIndexForElementAt"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eGenericSuperTypes eClassifier="#//feature/UpdateMultiValuedEFeature">
          <eTypeArguments eTypeParameter="#//feature/list/PermuteEList/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="attribute" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Feature/Attribute/1.0"
        nsPrefix="attribute">
      <eClassifiers xsi:type="ecore:EClass" name="UpdateEAttribute" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/EFeatureChange">
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceSingleValuedEAttribute">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/UpdateSingleValuedEFeature">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//ReplaciveAttributeChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InsertEAttributeValue">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/InsertInEList">
          <eTypeArguments eTypeParameter="#//feature/attribute/InsertEAttributeValue/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/InsertEAttributeValue/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//AdditiveAttributeChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/InsertEAttributeValue/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RemoveEAttributeValue">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/RemoveFromEList">
          <eTypeArguments eTypeParameter="#//feature/attribute/RemoveEAttributeValue/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/RemoveEAttributeValue/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//SubtractiveAttributeChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/RemoveEAttributeValue/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PermuteEAttributeValues">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/PermuteEList">
          <eTypeArguments eTypeParameter="#//feature/attribute/PermuteEAttributeValues/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/PermuteEAttributeValues/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="reference" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Feature/Reference/Containment/1.0"
        nsPrefix="reference">
      <eClassifiers xsi:type="ecore:EClass" name="UpdateEReference" abstract="true">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eOperations name="isContainment" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eGenericSuperTypes eClassifier="#//feature/EFeatureChange">
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceSingleValuedEReference">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/UpdateSingleValuedEFeature">
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceSingleValuedEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceSingleValuedEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//ReplaciveReferenceChange">
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceSingleValuedEReference/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InsertEReference">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/InsertInEList">
          <eTypeArguments eTypeParameter="#//feature/reference/InsertEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/InsertEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//AdditiveReferenceChange">
          <eTypeArguments eTypeParameter="#//feature/reference/InsertEReference/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RemoveEReference">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/RemoveFromEList">
          <eTypeArguments eTypeParameter="#//feature/reference/RemoveEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/RemoveEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//SubtractiveReferenceChange"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PermuteEReferenceValues">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/PermuteEList">
          <eTypeArguments eTypeParameter="#//feature/reference/PermuteEReferenceValues/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/PermuteEReferenceValues/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="object" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Object/1.0"
      nsPrefix="object">
    <eClassifiers xsi:type="ecore:EClass" name="EObjectChange" abstract="true" eSuperTypes="#//EChange"/>
    <eClassifiers xsi:type="ecore:EClass" name="CreateEObject">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//object/EObjectChange"/>
      <eGenericSuperTypes eClassifier="#//AdditiveReferenceChange">
        <eTypeArguments eTypeParameter="#//object/CreateEObject/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeleteEObject" eSuperTypes="#//object/EObjectChange #//SubtractiveReferenceChange">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="root" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Root/1.0"
      nsPrefix="root">
    <eClassifiers xsi:type="ecore:EClass" name="InsertRootEObject">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//AdditiveReferenceChange">
        <eTypeArguments eTypeParameter="#//root/InsertRootEObject/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RemoveRootEObject" eSuperTypes="#//SubtractiveReferenceChange"/>
  </eSubpackages>
  <eSubpackages name="compound" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Compound/1.0"
      nsPrefix="compound">
    <eClassifiers xsi:type="ecore:EClass" name="ECompoundChange" abstract="true" eSuperTypes="#//EChange">
      <eOperations name="getComposedChanges" lowerBound="1" upperBound="-1" eType="#//EChange"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateEObjectAndAdd" eSuperTypes="#//compound/ECompoundChange">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="createChange" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//object/CreateEObject">
          <eTypeArguments eTypeParameter="#//compound/CreateEObjectAndAdd/T"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="addChange" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//AdditiveReferenceChange">
          <eTypeArguments eTypeParameter="#//compound/CreateEObjectAndAdd/T"/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeleteEObjectAndSubtract" eSuperTypes="#//compound/ECompoundChange">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deleteChange" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//object/DeleteEObject">
          <eTypeArguments eTypeParameter="#//compound/DeleteEObjectAndSubtract/T"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subtractChange" lowerBound="1"
          eType="#//SubtractiveReferenceChange" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeleteEObjectCreateEObjectAndReplace"
        abstract="true" eSuperTypes="#//compound/ECompoundChange">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="R">
        <eBounds eClassifier="#//EChange"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deleteChange" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//object/DeleteEObject">
          <eTypeArguments eTypeParameter="#//compound/DeleteEObjectCreateEObjectAndReplace/T"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="createChange" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//object/CreateEObject">
          <eTypeArguments eTypeParameter="#//compound/DeleteEObjectCreateEObjectAndReplace/T"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="replaceChange" lowerBound="1"
          containment="true">
        <eGenericType eTypeParameter="#//compound/DeleteEObjectCreateEObjectAndReplace/R"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeleteEObjectCreateEObjectAndReplaceSingle">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//compound/DeleteEObjectCreateEObjectAndReplace">
        <eTypeArguments eTypeParameter="#//compound/DeleteEObjectCreateEObjectAndReplaceSingle/T"/>
        <eTypeArguments eClassifier="#//feature/reference/ReplaceSingleValuedEReference">
          <eTypeArguments eTypeParameter="#//compound/DeleteEObjectCreateEObjectAndReplaceSingle/T"/>
        </eTypeArguments>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeleteEObjectCreateEObjectAndReplaceInList">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//compound/DeleteEObjectCreateEObjectAndReplace">
        <eTypeArguments eTypeParameter="#//compound/DeleteEObjectCreateEObjectAndReplaceInList/T"/>
        <eTypeArguments eClassifier="#//compound/ReplaceInEList">
          <eTypeArguments eTypeParameter="#//compound/DeleteEObjectCreateEObjectAndReplaceInList/T"/>
        </eTypeArguments>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MoveEObject" eSuperTypes="#//compound/ECompoundChange">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subtractChange" lowerBound="1"
          eType="#//SubtractiveReferenceChange" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="addChange" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//AdditiveReferenceChange">
          <eTypeArguments eTypeParameter="#//compound/MoveEObject/T"/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReplaceInEList" eSuperTypes="#//compound/ECompoundChange">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="removeChange" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//feature/list/RemoveFromEList">
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/T"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="insertChange" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//feature/list/InsertInEList">
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/T"/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
