<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="change" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/1.0"
    nsPrefix="change">
  <eClassifiers xsi:type="ecore:EClass" name="EChange" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EAtomicChange" abstract="true" eSuperTypes="#//EChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveEChange" abstract="true" eSuperTypes="#//EAtomicChange">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getNewValue" lowerBound="1">
      <eGenericType eTypeParameter="#//AdditiveEChange/T"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubtractiveEChange" abstract="true"
      eSuperTypes="#//EAtomicChange">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getOldValue" lowerBound="1">
      <eGenericType eTypeParameter="#//SubtractiveEChange/T"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveEAttributeChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" lowerBound="1">
      <eGenericType eTypeParameter="#//AdditiveEAttributeChange/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//AdditiveEChange">
      <eTypeArguments eTypeParameter="#//AdditiveEAttributeChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubtractiveEAttributeChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldValue" lowerBound="1">
      <eGenericType eTypeParameter="#//SubtractiveEAttributeChange/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//SubtractiveEChange">
      <eTypeArguments eTypeParameter="#//SubtractiveEAttributeChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveEReferenceChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValue" lowerBound="1">
      <eGenericType eTypeParameter="#//AdditiveEReferenceChange/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCreate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="#//AdditiveEChange">
      <eTypeArguments eTypeParameter="#//AdditiveEReferenceChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubtractiveEReferenceChange" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldTUID" lowerBound="1"
        eType="#//TUID"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature2OldValueMap" lowerBound="1"
        transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDelete" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="#//SubtractiveEChange">
      <eTypeArguments eClassifier="#//TUID"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TUID" instanceClassName="edu.kit.ipd.sdq.vitruvius.framework.contracts.datatypes.TUID"/>
  <eSubpackages name="feature" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Feature/1.0"
      nsPrefix="feature">
    <eClassifiers xsi:type="ecore:EClass" name="EFeatureChange" abstract="true" eSuperTypes="#//EAtomicChange">
      <eTypeParameters name="A">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="F">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="affectedFeature" lowerBound="1">
        <eGenericType eTypeParameter="#//feature/EFeatureChange/F"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="affectedEObject" lowerBound="1">
        <eGenericType eTypeParameter="#//feature/EFeatureChange/A"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldTUIDOfAffectedEObject"
          lowerBound="1" eType="#//TUID"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UpdateEFeature" abstract="true" eSuperTypes="#//EAtomicChange"/>
    <eClassifiers xsi:type="ecore:EClass" name="UpdateMultiValuedEFeature" abstract="true"
        eSuperTypes="#//feature/UpdateEFeature"/>
    <eClassifiers xsi:type="ecore:EClass" name="UpdateSingleValuedEFeature" abstract="true"
        eSuperTypes="#//feature/UpdateEFeature"/>
    <eSubpackages name="list" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Feature/List/1.0"
        nsPrefix="list">
      <eClassifiers xsi:type="ecore:EClass" name="UpdateSingleEListEntry" abstract="true"
          eSuperTypes="#//feature/UpdateMultiValuedEFeature">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InsertInEList" abstract="true" eSuperTypes="#//feature/list/UpdateSingleEListEntry"/>
      <eClassifiers xsi:type="ecore:EClass" name="RemoveFromEList" abstract="true"
          eSuperTypes="#//feature/list/UpdateSingleEListEntry">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="removedObjectURIFragment"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral="0"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PermuteEList" abstract="true" eSuperTypes="#//feature/UpdateMultiValuedEFeature">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldIndex" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="newIndex" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="attribute" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Feature/Attribute/1.0"
        nsPrefix="attribute">
      <eClassifiers xsi:type="ecore:EClass" name="UpdateEAttribute" abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/EFeatureChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/UpdateEAttribute/A"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceSingleValuedEAttribute">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/UpdateSingleValuedEFeature"/>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/A"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//SubtractiveEAttributeChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//AdditiveEAttributeChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InsertEAttributeValue">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/InsertInEList"/>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/InsertEAttributeValue/A"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//AdditiveEAttributeChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/InsertEAttributeValue/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RemoveEAttributeValue">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/RemoveFromEList"/>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/RemoveEAttributeValue/A"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//SubtractiveEAttributeChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/RemoveEAttributeValue/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PermuteEAttributeValues">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/PermuteEList"/>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateEAttribute">
          <eTypeArguments eTypeParameter="#//feature/attribute/PermuteEAttributeValues/A"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="reference" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Feature/Reference/Containment/1.0"
        nsPrefix="reference">
      <eClassifiers xsi:type="ecore:EClass" name="UpdateEReference" abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eOperations name="isContainment" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eGenericSuperTypes eClassifier="#//feature/EFeatureChange">
          <eTypeArguments eTypeParameter="#//feature/reference/UpdateEReference/A"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceSingleValuedEReference">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/UpdateSingleValuedEFeature"/>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceSingleValuedEReference/A"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//SubtractiveEReferenceChange"/>
        <eGenericSuperTypes eClassifier="#//AdditiveEReferenceChange">
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceSingleValuedEReference/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InsertEReference">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/InsertInEList"/>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/InsertEReference/A"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//AdditiveEReferenceChange">
          <eTypeArguments eTypeParameter="#//feature/reference/InsertEReference/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RemoveEReference">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/RemoveFromEList"/>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/RemoveEReference/A"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//SubtractiveEReferenceChange"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PermuteEReferences">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/PermuteEList"/>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateEReference">
          <eTypeArguments eTypeParameter="#//feature/reference/PermuteEReferences/A"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="root" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Root/1.0"
      nsPrefix="root">
    <eClassifiers xsi:type="ecore:EClass" name="InsertRootEObject">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//AdditiveEReferenceChange">
        <eTypeArguments eTypeParameter="#//root/InsertRootEObject/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RemoveRootEObject" eSuperTypes="#//SubtractiveEReferenceChange"/>
  </eSubpackages>
  <eSubpackages name="compound" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/Compound/1.0"
      nsPrefix="compound">
    <eClassifiers xsi:type="ecore:EClass" name="ECompoundChange" abstract="true" eSuperTypes="#//EChange">
      <eOperations name="getAtomicChanges" lowerBound="1" upperBound="-1" eType="#//EAtomicChange"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MoveEObject" eSuperTypes="#//compound/ECompoundChange">
      <eTypeParameters name="A">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="B">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subtractWhereChange">
        <eGenericType eClassifier="#//feature/reference/UpdateEReference">
          <eTypeArguments eTypeParameter="#//compound/MoveEObject/A"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subtractWhatChange" lowerBound="1"
          eType="#//SubtractiveEReferenceChange" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="addWhereChange">
        <eGenericType eClassifier="#//feature/reference/UpdateEReference">
          <eTypeArguments eTypeParameter="#//compound/MoveEObject/B"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="addWhatChange" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//AdditiveEReferenceChange">
          <eTypeArguments eTypeParameter="#//compound/MoveEObject/T"/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReplaceInEList" eSuperTypes="#//compound/ECompoundChange">
      <eTypeParameters name="A">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="F">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eTypeParameters>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="R">
        <eBounds eClassifier="#//feature/list/RemoveFromEList"/>
        <eBounds eClassifier="#//feature/EFeatureChange">
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/A"/>
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/F"/>
        </eBounds>
        <eBounds eClassifier="#//SubtractiveEChange">
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/T"/>
        </eBounds>
      </eTypeParameters>
      <eTypeParameters name="I">
        <eBounds eClassifier="#//feature/list/InsertInEList"/>
        <eBounds eClassifier="#//feature/EFeatureChange">
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/A"/>
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/F"/>
        </eBounds>
        <eBounds eClassifier="#//AdditiveEReferenceChange">
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/T"/>
        </eBounds>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="removeChange" lowerBound="1"
          containment="true">
        <eGenericType eTypeParameter="#//compound/ReplaceInEList/R"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="insertChange" lowerBound="1"
          containment="true">
        <eGenericType eTypeParameter="#//compound/ReplaceInEList/I"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExplicitUnsetEFeature" eSuperTypes="#//compound/ECompoundChange">
      <eTypeParameters name="A">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="F">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eTypeParameters>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eTypeParameters>
      <eTypeParameters name="S">
        <eBounds eClassifier="#//feature/EFeatureChange">
          <eTypeArguments eTypeParameter="#//compound/ExplicitUnsetEFeature/A"/>
          <eTypeArguments eTypeParameter="#//compound/ExplicitUnsetEFeature/F"/>
        </eBounds>
        <eBounds eClassifier="#//SubtractiveEChange">
          <eTypeArguments eTypeParameter="#//compound/ExplicitUnsetEFeature/T"/>
        </eBounds>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subtractiveChanges" lowerBound="1"
          upperBound="-1" unsettable="true">
        <eGenericType eTypeParameter="#//compound/ExplicitUnsetEFeature/S"/>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
