package tools.vitruv.testutils.metamodels

import attribute_to_structure_struct_1.impl.Attribute_to_structure_struct_1FactoryImpl
import tools.vitruv.testutils.activeannotations.WithGeneratedRandomIds
import attribute_to_structure_struct_1.Identified
import attribute_to_structure_struct_1.Attribute_to_structure_struct_1Package

@WithGeneratedRandomIds(identifierMetaclass=Identified, identifierFeature=Attribute_to_structure_struct_1Package.
	IDENTIFIED__ID)
class RandomIdAttributeToStructureStructFactory extends Attribute_to_structure_struct_1FactoryImpl {
}
