package tools.vitruv.testutils.metamodels

import multicontainment_a.impl.Multicontainment_aFactoryImpl
import tools.vitruv.testutils.activeannotations.WithGeneratedRandomIds
import multicontainment_a.Identified
import multicontainment_a.Multicontainment_aPackage

@WithGeneratedRandomIds(identifierMetaclass=Identified, identifierFeature=Multicontainment_aPackage.IDENTIFIED__ID)
class RandomIdMulticontainmentAFactory extends Multicontainment_aFactoryImpl {
}
