/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package edu.kit.ipd.sdq.vitruvius.dsls.mirBase.impl;

import edu.kit.ipd.sdq.vitruvius.dsls.mirBase.MirBasePackage;
import edu.kit.ipd.sdq.vitruvius.dsls.mirBase.NamedModelElement;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Named Model Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NamedModelElementImpl extends MinimalEObjectImpl.Container implements NamedModelElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NamedModelElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MirBasePackage.Literals.NAMED_MODEL_ELEMENT;
  }

} //NamedModelElementImpl
