/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.reactions.reactionsLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.reactionsLanguage.CorrespondingObjectCodeBlock;
import tools.vitruv.dsls.reactions.reactionsLanguage.ReactionsLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Corresponding Object Code Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CorrespondingObjectCodeBlockImpl extends CodeBlockImpl implements CorrespondingObjectCodeBlock
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CorrespondingObjectCodeBlockImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReactionsLanguagePackage.Literals.CORRESPONDING_OBJECT_CODE_BLOCK;
  }

} //CorrespondingObjectCodeBlockImpl
