/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package tools.vitruv.dsls.mapping.mappingLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.mapping.mappingLanguage.BodyConstraintBlock;
import tools.vitruv.dsls.mapping.mappingLanguage.MappingLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Body Constraint Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BodyConstraintBlockImpl extends ConstraintBlockImpl implements BodyConstraintBlock
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BodyConstraintBlockImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MappingLanguagePackage.Literals.BODY_CONSTRAINT_BLOCK;
  }

} //BodyConstraintBlockImpl
