/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.mapping.mappingLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.mapping.mappingLanguage.ConstraintNullLiteral;
import tools.vitruv.dsls.mapping.mappingLanguage.MappingLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Constraint Null Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConstraintNullLiteralImpl extends ConstraintLiteralImpl implements ConstraintNullLiteral
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConstraintNullLiteralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MappingLanguagePackage.Literals.CONSTRAINT_NULL_LITERAL;
  }

} //ConstraintNullLiteralImpl
