/*
 * generated by Xtext 2.10.0
 */
package tools.vitruvius.dsls.response;

import com.google.inject.Guice;
import com.google.inject.Injector;
import tools.vitruvius.dsls.mirbase.MirBaseStandaloneSetup;
import tools.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.resource.IResourceFactory;
import org.eclipse.xtext.resource.IResourceServiceProvider;

@SuppressWarnings("all")
public class ResponseLanguageStandaloneSetupGenerated implements ISetup {

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		MirBaseStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new ResponseLanguageRuntimeModule());
	}
	
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.kit.edu/ipd/sdq/vitruvius/dsls/response/ResponseLanguage")) {
			EPackage.Registry.INSTANCE.put("http://www.kit.edu/ipd/sdq/vitruvius/dsls/response/ResponseLanguage", ResponseLanguagePackage.eINSTANCE);
		}
		IResourceFactory resourceFactory = injector.getInstance(IResourceFactory.class);
		IResourceServiceProvider serviceProvider = injector.getInstance(IResourceServiceProvider.class);
		
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("response", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("response", serviceProvider);
	}
}
