/*
 * generated by Xtext 2.12.0
 */
package tools.vitruv.dsls.mappings


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MappingsLanguageRuntimeModule extends AbstractMappingsLanguageRuntimeModule {
}
