<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="change" nsURI="http://edu.kit.ipd.sdq.vitruvius/Change/1.0"
    nsPrefix="change">
  <eClassifiers xsi:type="ecore:EClass" name="EChange" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectChange" abstract="true" eSuperTypes="#//EChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="changedEObject" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFeatureChange" abstract="true" eSuperTypes="#//EChange">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedFeature" lowerBound="1">
      <eGenericType eTypeParameter="#//EFeatureChange/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedEObject" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAttributeChange" abstract="true">
    <eGenericSuperTypes eClassifier="#//EFeatureChange">
      <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EReferenceChange" abstract="true">
    <eGenericSuperTypes eClassifier="#//EFeatureChange">
      <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateEObject" abstract="true" eSuperTypes="#//EObjectChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateNonRootEObject">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//CreateEObject"/>
    <eGenericSuperTypes eClassifier="#//UpdateEContainmentReference">
      <eTypeArguments eTypeParameter="#//CreateNonRootEObject/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateRootEObject" eSuperTypes="#//CreateEObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateEFeature" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getNewValue" lowerBound="1">
      <eGenericType eTypeParameter="#//UpdateEFeature/T"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnsetEFeature">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//EFeatureChange">
      <eTypeArguments eTypeParameter="#//UnsetEFeature/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateEAttribute">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" lowerBound="1">
      <eGenericType eTypeParameter="#//UpdateEAttribute/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//UpdateEFeature">
      <eTypeArguments eTypeParameter="#//UpdateEAttribute/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//EAttributeChange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateEReference">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValue" lowerBound="1">
      <eGenericType eTypeParameter="#//UpdateEReference/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//UpdateEFeature">
      <eTypeArguments eTypeParameter="#//UpdateEReference/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//EReferenceChange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateEContainmentReference">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//UpdateEReference">
      <eTypeArguments eTypeParameter="#//UpdateEContainmentReference/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteEObject" abstract="true" eSuperTypes="#//EObjectChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteNonRootEObject">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//DeleteRootEObject"/>
    <eGenericSuperTypes eClassifier="#//UpdateEContainmentReference">
      <eTypeArguments eTypeParameter="#//DeleteNonRootEObject/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteRootEObject" eSuperTypes="#//DeleteEObject"/>
</ecore:EPackage>
