/**
 * generated by Xtext 2.9.2
 */
package tools.vitruvius.dsls.mapping.mappingLanguage.impl;

import tools.vitruvius.dsls.mapping.mappingLanguage.ConstraintLiteral;
import tools.vitruvius.dsls.mapping.mappingLanguage.MappingLanguagePackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Constraint Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConstraintLiteralImpl extends MinimalEObjectImpl.Container implements ConstraintLiteral
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConstraintLiteralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MappingLanguagePackage.Literals.CONSTRAINT_LITERAL;
  }

} //ConstraintLiteralImpl
