/**
 * generated by Xtext 2.10.0
 */
package tools.vitruvius.dsls.response.responseLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arbitrary Model Element Change</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage#getArbitraryModelElementChange()
 * @model
 * @generated
 */
public interface ArbitraryModelElementChange extends ModelChange
{
} // ArbitraryModelElementChange
