/**
 * generated by Xtext 2.10.0
 */
package tools.vitruvius.dsls.response.responseLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atomic Multi Valued Feature Change</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage#getAtomicMultiValuedFeatureChange()
 * @model
 * @generated
 */
public interface AtomicMultiValuedFeatureChange extends AtomicFeatureChange
{
} // AtomicMultiValuedFeatureChange
