/**
 * generated by Xtext 2.10.0
 */
package tools.vitruvius.dsls.response.responseLanguage;

import tools.vitruvius.dsls.mirbase.mirBase.FeatureOfElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atomic Feature Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruvius.dsls.response.responseLanguage.AtomicFeatureChange#getChangedFeature <em>Changed Feature</em>}</li>
 * </ul>
 *
 * @see tools.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage#getAtomicFeatureChange()
 * @model
 * @generated
 */
public interface AtomicFeatureChange extends AtomicConcreteModelElementChange
{
  /**
   * Returns the value of the '<em><b>Changed Feature</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Changed Feature</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Changed Feature</em>' containment reference.
   * @see #setChangedFeature(FeatureOfElement)
   * @see tools.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage#getAtomicFeatureChange_ChangedFeature()
   * @model containment="true"
   * @generated
   */
  FeatureOfElement getChangedFeature();

  /**
   * Sets the value of the '{@link tools.vitruvius.dsls.response.responseLanguage.AtomicFeatureChange#getChangedFeature <em>Changed Feature</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Changed Feature</em>' containment reference.
   * @see #getChangedFeature()
   * @generated
   */
  void setChangedFeature(FeatureOfElement value);

} // AtomicFeatureChange
