/**
 * generated by Xtext 2.10.0
 */
package tools.vitruvius.dsls.response.responseLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Corresponding Object Code Block</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage#getCorrespondingObjectCodeBlock()
 * @model
 * @generated
 */
public interface CorrespondingObjectCodeBlock extends CodeBlock
{
} // CorrespondingObjectCodeBlock
