/**
 * generated by Xtext 2.10.0
 */
package tools.vitruvius.dsls.response.responseLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Existing Element Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage#getExistingElementReference()
 * @model
 * @generated
 */
public interface ExistingElementReference extends CodeBlock
{
} // ExistingElementReference
