package tools.vitruv.demo.applications.familiespersons.families2persons

class FamiliesToPersonsChangePropagationSpecification extends mir.reactions.familiesToPersons.FamiliesToPersonsChangePropagationSpecification {

}