package tools.vitruv.applications.pcmjava.tests.pojotransformations.gplimplementation.java2pcm

import tools.vitruv.applications.pcmjava.tests.pojotransformations.java2pcm.JaMoPPParameterMappingTransformationTest

class JaMoPPParameterMappingGplTransformationTest extends JaMoPPParameterMappingTransformationTest {
	override protected createChange2CommandTransformingProviding() {
		Change2CommandTransformingProvidingFactory.createJava2PcmGplImplementationTransformingProviding();
	}
}