/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.reactions.reactionsLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.reactionsLanguage.AtomicConcreteModelElementChange;
import tools.vitruv.dsls.reactions.reactionsLanguage.ReactionsLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atomic Concrete Model Element Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AtomicConcreteModelElementChangeImpl extends ConcreteModelElementChangeImpl implements AtomicConcreteModelElementChange
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtomicConcreteModelElementChangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReactionsLanguagePackage.Literals.ATOMIC_CONCRETE_MODEL_ELEMENT_CHANGE;
  }

} //AtomicConcreteModelElementChangeImpl
