/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.reactions.reactionsLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.reactionsLanguage.MultiValuedFeatureRemoveChange;
import tools.vitruv.dsls.reactions.reactionsLanguage.ReactionsLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Multi Valued Feature Remove Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MultiValuedFeatureRemoveChangeImpl extends AtomicMultiValuedFeatureChangeImpl implements MultiValuedFeatureRemoveChange
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MultiValuedFeatureRemoveChangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReactionsLanguagePackage.Literals.MULTI_VALUED_FEATURE_REMOVE_CHANGE;
  }

} //MultiValuedFeatureRemoveChangeImpl
