/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.reactions.reactionsLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.reactionsLanguage.ReactionsLanguagePackage;
import tools.vitruv.dsls.reactions.reactionsLanguage.SingleValuedFeatureReplace;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Single Valued Feature Replace</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SingleValuedFeatureReplaceImpl extends AtomicSingleValuedFeatureChangeImpl implements SingleValuedFeatureReplace
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SingleValuedFeatureReplaceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReactionsLanguagePackage.Literals.SINGLE_VALUED_FEATURE_REPLACE;
  }

} //SingleValuedFeatureReplaceImpl
