package tools.vitruv.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository

import tools.vitruv.applications.pcmjava.tests.pojotransformations.pcm2java.repository.CompositeComponentMappingTransformationTest

class CompositeComponentMappingGplTransformationTest extends CompositeComponentMappingTransformationTest {
	override protected createChange2CommandTransformingProviding() {
		Change2CommandTransformingProvidingFactory.createPcm2JavaGplImplementationTransformingProviding();
	}
}