/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.impl;

import edu.kit.ipd.sdq.vitruvius.dsls.mirbase.mirBase.MetamodelReference;

import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ArbitraryModelElementChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Arbitrary Model Element Change</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.impl.ArbitraryModelElementChangeImpl#getChangedModel <em>Changed Model</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ArbitraryModelElementChangeImpl extends ModelChangeImpl implements ArbitraryModelElementChange
{
  /**
   * The cached value of the '{@link #getChangedModel() <em>Changed Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChangedModel()
   * @generated
   * @ordered
   */
  protected MetamodelReference changedModel;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ArbitraryModelElementChangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ResponseLanguagePackage.Literals.ARBITRARY_MODEL_ELEMENT_CHANGE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MetamodelReference getChangedModel()
  {
    return changedModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetChangedModel(MetamodelReference newChangedModel, NotificationChain msgs)
  {
    MetamodelReference oldChangedModel = changedModel;
    changedModel = newChangedModel;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ResponseLanguagePackage.ARBITRARY_MODEL_ELEMENT_CHANGE__CHANGED_MODEL, oldChangedModel, newChangedModel);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setChangedModel(MetamodelReference newChangedModel)
  {
    if (newChangedModel != changedModel)
    {
      NotificationChain msgs = null;
      if (changedModel != null)
        msgs = ((InternalEObject)changedModel).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ResponseLanguagePackage.ARBITRARY_MODEL_ELEMENT_CHANGE__CHANGED_MODEL, null, msgs);
      if (newChangedModel != null)
        msgs = ((InternalEObject)newChangedModel).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ResponseLanguagePackage.ARBITRARY_MODEL_ELEMENT_CHANGE__CHANGED_MODEL, null, msgs);
      msgs = basicSetChangedModel(newChangedModel, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResponseLanguagePackage.ARBITRARY_MODEL_ELEMENT_CHANGE__CHANGED_MODEL, newChangedModel, newChangedModel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ResponseLanguagePackage.ARBITRARY_MODEL_ELEMENT_CHANGE__CHANGED_MODEL:
        return basicSetChangedModel(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ResponseLanguagePackage.ARBITRARY_MODEL_ELEMENT_CHANGE__CHANGED_MODEL:
        return getChangedModel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ResponseLanguagePackage.ARBITRARY_MODEL_ELEMENT_CHANGE__CHANGED_MODEL:
        setChangedModel((MetamodelReference)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ResponseLanguagePackage.ARBITRARY_MODEL_ELEMENT_CHANGE__CHANGED_MODEL:
        setChangedModel((MetamodelReference)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ResponseLanguagePackage.ARBITRARY_MODEL_ELEMENT_CHANGE__CHANGED_MODEL:
        return changedModel != null;
    }
    return super.eIsSet(featureID);
  }

} //ArbitraryModelElementChangeImpl
