/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.impl;

import edu.kit.ipd.sdq.vitruvius.dsls.mirbase.mirBase.MirBasePackage;

import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ArbitraryModelElementChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ArbitraryTargetMetamodelInstanceUpdate;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.AtomicConcreteModelElementChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.AtomicFeatureChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.AtomicMultiValuedFeatureChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.AtomicRootObjectChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.AtomicSingleValuedFeatureChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.CodeBlock;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ConcreteModelElementChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ConcreteTargetModelChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.CorrespondingModelElementCreate;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.CorrespondingModelElementDelete;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.CorrespondingModelElementRetrieve;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.CorrespondingModelElementRetrieveOrDelete;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.CorrespondingModelElementSpecification;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.CorrespondingModelElementSpecificationWithPrecondition;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.CorrespondingObjectCodeBlock;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.Effects;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ExecutionCodeBlock;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.InsertRootChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.InvariantViolationEvent;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ModelChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ModelPathCodeBlock;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ModelPersistence;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.MultiValuedFeatureInsertChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.MultiValuedFeaturePermuteChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.MultiValuedFeatureRemoveChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.PreconditionCodeBlock;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.RemoveRootChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.Response;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ResponseFile;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ResponseLanguageFactory;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.SingleValuedFeatureCreate;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.SingleValuedFeatureDelete;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.SingleValuedFeatureReplace;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.TargetChange;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.Trigger;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.eclipse.xtext.xbase.XbasePackage;

import org.eclipse.xtext.xtype.XtypePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ResponseLanguagePackageImpl extends EPackageImpl implements ResponseLanguagePackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass responseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass effectsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass targetChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass concreteTargetModelChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass correspondingModelElementCreateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelPersistenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass correspondingModelElementDeleteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass correspondingModelElementRetrieveEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass correspondingModelElementRetrieveOrDeleteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass correspondingModelElementSpecificationWithPreconditionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass correspondingModelElementSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass arbitraryTargetMetamodelInstanceUpdateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass preconditionCodeBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass correspondingObjectCodeBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelPathCodeBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass executionCodeBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass codeBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass invariantViolationEventEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass triggerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass concreteModelElementChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atomicConcreteModelElementChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atomicRootObjectChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atomicFeatureChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atomicMultiValuedFeatureChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atomicSingleValuedFeatureChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass arbitraryModelElementChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass responseFileEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass insertRootChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass removeRootChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiValuedFeatureInsertChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiValuedFeatureRemoveChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiValuedFeaturePermuteChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass singleValuedFeatureCreateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass singleValuedFeatureDeleteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass singleValuedFeatureReplaceEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage#eNS_URI
   * @see #init()
   * @generated
   */
  private ResponseLanguagePackageImpl()
  {
    super(eNS_URI, ResponseLanguageFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link ResponseLanguagePackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static ResponseLanguagePackage init()
  {
    if (isInited) return (ResponseLanguagePackage)EPackage.Registry.INSTANCE.getEPackage(ResponseLanguagePackage.eNS_URI);

    // Obtain or create and register package
    ResponseLanguagePackageImpl theResponseLanguagePackage = (ResponseLanguagePackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof ResponseLanguagePackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new ResponseLanguagePackageImpl());

    isInited = true;

    // Initialize simple dependencies
    MirBasePackage.eINSTANCE.eClass();
    XbasePackage.eINSTANCE.eClass();
    XtypePackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theResponseLanguagePackage.createPackageContents();

    // Initialize created meta-data
    theResponseLanguagePackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theResponseLanguagePackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(ResponseLanguagePackage.eNS_URI, theResponseLanguagePackage);
    return theResponseLanguagePackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getResponse()
  {
    return responseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getResponse_Documentation()
  {
    return (EAttribute)responseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getResponse_Name()
  {
    return (EAttribute)responseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getResponse_Trigger()
  {
    return (EReference)responseEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getResponse_Effects()
  {
    return (EReference)responseEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEffects()
  {
    return effectsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEffects_TargetChange()
  {
    return (EReference)effectsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEffects_CodeBlock()
  {
    return (EReference)effectsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTargetChange()
  {
    return targetChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getConcreteTargetModelChange()
  {
    return concreteTargetModelChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getConcreteTargetModelChange_RetrieveElements()
  {
    return (EReference)concreteTargetModelChangeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getConcreteTargetModelChange_DeleteElements()
  {
    return (EReference)concreteTargetModelChangeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getConcreteTargetModelChange_CreateElements()
  {
    return (EReference)concreteTargetModelChangeEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCorrespondingModelElementCreate()
  {
    return correspondingModelElementCreateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCorrespondingModelElementCreate_PersistAsRoot()
  {
    return (EReference)correspondingModelElementCreateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModelPersistence()
  {
    return modelPersistenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getModelPersistence_UseRelativeToSource()
  {
    return (EAttribute)modelPersistenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getModelPersistence_UseRelativeToProject()
  {
    return (EAttribute)modelPersistenceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModelPersistence_ModelPath()
  {
    return (EReference)modelPersistenceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCorrespondingModelElementDelete()
  {
    return correspondingModelElementDeleteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCorrespondingModelElementRetrieve()
  {
    return correspondingModelElementRetrieveEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCorrespondingModelElementRetrieve_RenamedModelFileName()
  {
    return (EReference)correspondingModelElementRetrieveEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCorrespondingModelElementRetrieveOrDelete()
  {
    return correspondingModelElementRetrieveOrDeleteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCorrespondingModelElementSpecificationWithPrecondition()
  {
    return correspondingModelElementSpecificationWithPreconditionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCorrespondingModelElementSpecificationWithPrecondition_Precondition()
  {
    return (EReference)correspondingModelElementSpecificationWithPreconditionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCorrespondingModelElementSpecification()
  {
    return correspondingModelElementSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCorrespondingModelElementSpecification_Name()
  {
    return (EAttribute)correspondingModelElementSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCorrespondingModelElementSpecification_ElementType()
  {
    return (EReference)correspondingModelElementSpecificationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCorrespondingModelElementSpecification_CorrespondenceSource()
  {
    return (EReference)correspondingModelElementSpecificationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getArbitraryTargetMetamodelInstanceUpdate()
  {
    return arbitraryTargetMetamodelInstanceUpdateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getArbitraryTargetMetamodelInstanceUpdate_MetamodelReference()
  {
    return (EReference)arbitraryTargetMetamodelInstanceUpdateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPreconditionCodeBlock()
  {
    return preconditionCodeBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCorrespondingObjectCodeBlock()
  {
    return correspondingObjectCodeBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModelPathCodeBlock()
  {
    return modelPathCodeBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExecutionCodeBlock()
  {
    return executionCodeBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCodeBlock()
  {
    return codeBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCodeBlock_Code()
  {
    return (EReference)codeBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getInvariantViolationEvent()
  {
    return invariantViolationEventEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getInvariantViolationEvent_Violation()
  {
    return (EReference)invariantViolationEventEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTrigger()
  {
    return triggerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTrigger_Precondition()
  {
    return (EReference)triggerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModelChange()
  {
    return modelChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getConcreteModelElementChange()
  {
    return concreteModelElementChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAtomicConcreteModelElementChange()
  {
    return atomicConcreteModelElementChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAtomicRootObjectChange()
  {
    return atomicRootObjectChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAtomicRootObjectChange_ChangedElement()
  {
    return (EReference)atomicRootObjectChangeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAtomicFeatureChange()
  {
    return atomicFeatureChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAtomicFeatureChange_ChangedFeature()
  {
    return (EReference)atomicFeatureChangeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAtomicMultiValuedFeatureChange()
  {
    return atomicMultiValuedFeatureChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAtomicSingleValuedFeatureChange()
  {
    return atomicSingleValuedFeatureChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getArbitraryModelElementChange()
  {
    return arbitraryModelElementChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getArbitraryModelElementChange_ChangedModel()
  {
    return (EReference)arbitraryModelElementChangeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getResponseFile()
  {
    return responseFileEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getResponseFile_NamespaceImports()
  {
    return (EReference)responseFileEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getResponseFile_Responses()
  {
    return (EReference)responseFileEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getInsertRootChange()
  {
    return insertRootChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRemoveRootChange()
  {
    return removeRootChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMultiValuedFeatureInsertChange()
  {
    return multiValuedFeatureInsertChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMultiValuedFeatureRemoveChange()
  {
    return multiValuedFeatureRemoveChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMultiValuedFeaturePermuteChange()
  {
    return multiValuedFeaturePermuteChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSingleValuedFeatureCreate()
  {
    return singleValuedFeatureCreateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSingleValuedFeatureDelete()
  {
    return singleValuedFeatureDeleteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSingleValuedFeatureReplace()
  {
    return singleValuedFeatureReplaceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ResponseLanguageFactory getResponseLanguageFactory()
  {
    return (ResponseLanguageFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    responseEClass = createEClass(RESPONSE);
    createEAttribute(responseEClass, RESPONSE__DOCUMENTATION);
    createEAttribute(responseEClass, RESPONSE__NAME);
    createEReference(responseEClass, RESPONSE__TRIGGER);
    createEReference(responseEClass, RESPONSE__EFFECTS);

    effectsEClass = createEClass(EFFECTS);
    createEReference(effectsEClass, EFFECTS__TARGET_CHANGE);
    createEReference(effectsEClass, EFFECTS__CODE_BLOCK);

    targetChangeEClass = createEClass(TARGET_CHANGE);

    concreteTargetModelChangeEClass = createEClass(CONCRETE_TARGET_MODEL_CHANGE);
    createEReference(concreteTargetModelChangeEClass, CONCRETE_TARGET_MODEL_CHANGE__RETRIEVE_ELEMENTS);
    createEReference(concreteTargetModelChangeEClass, CONCRETE_TARGET_MODEL_CHANGE__DELETE_ELEMENTS);
    createEReference(concreteTargetModelChangeEClass, CONCRETE_TARGET_MODEL_CHANGE__CREATE_ELEMENTS);

    correspondingModelElementCreateEClass = createEClass(CORRESPONDING_MODEL_ELEMENT_CREATE);
    createEReference(correspondingModelElementCreateEClass, CORRESPONDING_MODEL_ELEMENT_CREATE__PERSIST_AS_ROOT);

    modelPersistenceEClass = createEClass(MODEL_PERSISTENCE);
    createEAttribute(modelPersistenceEClass, MODEL_PERSISTENCE__USE_RELATIVE_TO_SOURCE);
    createEAttribute(modelPersistenceEClass, MODEL_PERSISTENCE__USE_RELATIVE_TO_PROJECT);
    createEReference(modelPersistenceEClass, MODEL_PERSISTENCE__MODEL_PATH);

    correspondingModelElementDeleteEClass = createEClass(CORRESPONDING_MODEL_ELEMENT_DELETE);

    correspondingModelElementRetrieveEClass = createEClass(CORRESPONDING_MODEL_ELEMENT_RETRIEVE);
    createEReference(correspondingModelElementRetrieveEClass, CORRESPONDING_MODEL_ELEMENT_RETRIEVE__RENAMED_MODEL_FILE_NAME);

    correspondingModelElementRetrieveOrDeleteEClass = createEClass(CORRESPONDING_MODEL_ELEMENT_RETRIEVE_OR_DELETE);

    correspondingModelElementSpecificationWithPreconditionEClass = createEClass(CORRESPONDING_MODEL_ELEMENT_SPECIFICATION_WITH_PRECONDITION);
    createEReference(correspondingModelElementSpecificationWithPreconditionEClass, CORRESPONDING_MODEL_ELEMENT_SPECIFICATION_WITH_PRECONDITION__PRECONDITION);

    correspondingModelElementSpecificationEClass = createEClass(CORRESPONDING_MODEL_ELEMENT_SPECIFICATION);
    createEAttribute(correspondingModelElementSpecificationEClass, CORRESPONDING_MODEL_ELEMENT_SPECIFICATION__NAME);
    createEReference(correspondingModelElementSpecificationEClass, CORRESPONDING_MODEL_ELEMENT_SPECIFICATION__ELEMENT_TYPE);
    createEReference(correspondingModelElementSpecificationEClass, CORRESPONDING_MODEL_ELEMENT_SPECIFICATION__CORRESPONDENCE_SOURCE);

    arbitraryTargetMetamodelInstanceUpdateEClass = createEClass(ARBITRARY_TARGET_METAMODEL_INSTANCE_UPDATE);
    createEReference(arbitraryTargetMetamodelInstanceUpdateEClass, ARBITRARY_TARGET_METAMODEL_INSTANCE_UPDATE__METAMODEL_REFERENCE);

    preconditionCodeBlockEClass = createEClass(PRECONDITION_CODE_BLOCK);

    correspondingObjectCodeBlockEClass = createEClass(CORRESPONDING_OBJECT_CODE_BLOCK);

    modelPathCodeBlockEClass = createEClass(MODEL_PATH_CODE_BLOCK);

    executionCodeBlockEClass = createEClass(EXECUTION_CODE_BLOCK);

    codeBlockEClass = createEClass(CODE_BLOCK);
    createEReference(codeBlockEClass, CODE_BLOCK__CODE);

    invariantViolationEventEClass = createEClass(INVARIANT_VIOLATION_EVENT);
    createEReference(invariantViolationEventEClass, INVARIANT_VIOLATION_EVENT__VIOLATION);

    triggerEClass = createEClass(TRIGGER);
    createEReference(triggerEClass, TRIGGER__PRECONDITION);

    modelChangeEClass = createEClass(MODEL_CHANGE);

    concreteModelElementChangeEClass = createEClass(CONCRETE_MODEL_ELEMENT_CHANGE);

    atomicConcreteModelElementChangeEClass = createEClass(ATOMIC_CONCRETE_MODEL_ELEMENT_CHANGE);

    atomicRootObjectChangeEClass = createEClass(ATOMIC_ROOT_OBJECT_CHANGE);
    createEReference(atomicRootObjectChangeEClass, ATOMIC_ROOT_OBJECT_CHANGE__CHANGED_ELEMENT);

    atomicFeatureChangeEClass = createEClass(ATOMIC_FEATURE_CHANGE);
    createEReference(atomicFeatureChangeEClass, ATOMIC_FEATURE_CHANGE__CHANGED_FEATURE);

    atomicMultiValuedFeatureChangeEClass = createEClass(ATOMIC_MULTI_VALUED_FEATURE_CHANGE);

    atomicSingleValuedFeatureChangeEClass = createEClass(ATOMIC_SINGLE_VALUED_FEATURE_CHANGE);

    arbitraryModelElementChangeEClass = createEClass(ARBITRARY_MODEL_ELEMENT_CHANGE);
    createEReference(arbitraryModelElementChangeEClass, ARBITRARY_MODEL_ELEMENT_CHANGE__CHANGED_MODEL);

    responseFileEClass = createEClass(RESPONSE_FILE);
    createEReference(responseFileEClass, RESPONSE_FILE__NAMESPACE_IMPORTS);
    createEReference(responseFileEClass, RESPONSE_FILE__RESPONSES);

    insertRootChangeEClass = createEClass(INSERT_ROOT_CHANGE);

    removeRootChangeEClass = createEClass(REMOVE_ROOT_CHANGE);

    multiValuedFeatureInsertChangeEClass = createEClass(MULTI_VALUED_FEATURE_INSERT_CHANGE);

    multiValuedFeatureRemoveChangeEClass = createEClass(MULTI_VALUED_FEATURE_REMOVE_CHANGE);

    multiValuedFeaturePermuteChangeEClass = createEClass(MULTI_VALUED_FEATURE_PERMUTE_CHANGE);

    singleValuedFeatureCreateEClass = createEClass(SINGLE_VALUED_FEATURE_CREATE);

    singleValuedFeatureDeleteEClass = createEClass(SINGLE_VALUED_FEATURE_DELETE);

    singleValuedFeatureReplaceEClass = createEClass(SINGLE_VALUED_FEATURE_REPLACE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    MirBasePackage theMirBasePackage = (MirBasePackage)EPackage.Registry.INSTANCE.getEPackage(MirBasePackage.eNS_URI);
    XbasePackage theXbasePackage = (XbasePackage)EPackage.Registry.INSTANCE.getEPackage(XbasePackage.eNS_URI);
    XtypePackage theXtypePackage = (XtypePackage)EPackage.Registry.INSTANCE.getEPackage(XtypePackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    concreteTargetModelChangeEClass.getESuperTypes().add(this.getTargetChange());
    correspondingModelElementCreateEClass.getESuperTypes().add(this.getCorrespondingModelElementSpecification());
    correspondingModelElementDeleteEClass.getESuperTypes().add(this.getCorrespondingModelElementRetrieveOrDelete());
    correspondingModelElementDeleteEClass.getESuperTypes().add(this.getCorrespondingModelElementSpecificationWithPrecondition());
    correspondingModelElementDeleteEClass.getESuperTypes().add(this.getCorrespondingModelElementSpecification());
    correspondingModelElementRetrieveEClass.getESuperTypes().add(this.getCorrespondingModelElementRetrieveOrDelete());
    correspondingModelElementRetrieveEClass.getESuperTypes().add(this.getCorrespondingModelElementSpecificationWithPrecondition());
    correspondingModelElementRetrieveEClass.getESuperTypes().add(this.getCorrespondingModelElementSpecification());
    correspondingModelElementRetrieveOrDeleteEClass.getESuperTypes().add(this.getCorrespondingModelElementSpecificationWithPrecondition());
    correspondingModelElementRetrieveOrDeleteEClass.getESuperTypes().add(this.getCorrespondingModelElementSpecification());
    correspondingModelElementSpecificationWithPreconditionEClass.getESuperTypes().add(this.getCorrespondingModelElementSpecification());
    arbitraryTargetMetamodelInstanceUpdateEClass.getESuperTypes().add(this.getTargetChange());
    preconditionCodeBlockEClass.getESuperTypes().add(this.getCodeBlock());
    correspondingObjectCodeBlockEClass.getESuperTypes().add(this.getCodeBlock());
    modelPathCodeBlockEClass.getESuperTypes().add(this.getCodeBlock());
    executionCodeBlockEClass.getESuperTypes().add(this.getCodeBlock());
    invariantViolationEventEClass.getESuperTypes().add(this.getTrigger());
    modelChangeEClass.getESuperTypes().add(this.getTrigger());
    concreteModelElementChangeEClass.getESuperTypes().add(this.getModelChange());
    atomicConcreteModelElementChangeEClass.getESuperTypes().add(this.getConcreteModelElementChange());
    atomicRootObjectChangeEClass.getESuperTypes().add(this.getAtomicConcreteModelElementChange());
    atomicFeatureChangeEClass.getESuperTypes().add(this.getAtomicConcreteModelElementChange());
    atomicMultiValuedFeatureChangeEClass.getESuperTypes().add(this.getAtomicFeatureChange());
    atomicSingleValuedFeatureChangeEClass.getESuperTypes().add(this.getAtomicFeatureChange());
    arbitraryModelElementChangeEClass.getESuperTypes().add(this.getModelChange());
    responseFileEClass.getESuperTypes().add(theMirBasePackage.getMirBaseFile());
    insertRootChangeEClass.getESuperTypes().add(this.getAtomicRootObjectChange());
    removeRootChangeEClass.getESuperTypes().add(this.getAtomicRootObjectChange());
    multiValuedFeatureInsertChangeEClass.getESuperTypes().add(this.getAtomicMultiValuedFeatureChange());
    multiValuedFeatureRemoveChangeEClass.getESuperTypes().add(this.getAtomicMultiValuedFeatureChange());
    multiValuedFeaturePermuteChangeEClass.getESuperTypes().add(this.getAtomicMultiValuedFeatureChange());
    singleValuedFeatureCreateEClass.getESuperTypes().add(this.getAtomicSingleValuedFeatureChange());
    singleValuedFeatureDeleteEClass.getESuperTypes().add(this.getAtomicSingleValuedFeatureChange());
    singleValuedFeatureReplaceEClass.getESuperTypes().add(this.getAtomicSingleValuedFeatureChange());

    // Initialize classes and features; add operations and parameters
    initEClass(responseEClass, Response.class, "Response", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getResponse_Documentation(), ecorePackage.getEString(), "documentation", null, 0, 1, Response.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getResponse_Name(), ecorePackage.getEString(), "name", null, 0, 1, Response.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getResponse_Trigger(), this.getTrigger(), null, "trigger", null, 0, 1, Response.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getResponse_Effects(), this.getEffects(), null, "effects", null, 0, 1, Response.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(effectsEClass, Effects.class, "Effects", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEffects_TargetChange(), this.getTargetChange(), null, "targetChange", null, 0, 1, Effects.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEffects_CodeBlock(), this.getExecutionCodeBlock(), null, "codeBlock", null, 0, 1, Effects.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(targetChangeEClass, TargetChange.class, "TargetChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(concreteTargetModelChangeEClass, ConcreteTargetModelChange.class, "ConcreteTargetModelChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getConcreteTargetModelChange_RetrieveElements(), this.getCorrespondingModelElementRetrieve(), null, "retrieveElements", null, 0, -1, ConcreteTargetModelChange.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConcreteTargetModelChange_DeleteElements(), this.getCorrespondingModelElementDelete(), null, "deleteElements", null, 0, -1, ConcreteTargetModelChange.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConcreteTargetModelChange_CreateElements(), this.getCorrespondingModelElementCreate(), null, "createElements", null, 0, -1, ConcreteTargetModelChange.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(correspondingModelElementCreateEClass, CorrespondingModelElementCreate.class, "CorrespondingModelElementCreate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCorrespondingModelElementCreate_PersistAsRoot(), this.getModelPersistence(), null, "persistAsRoot", null, 0, 1, CorrespondingModelElementCreate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelPersistenceEClass, ModelPersistence.class, "ModelPersistence", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getModelPersistence_UseRelativeToSource(), ecorePackage.getEBoolean(), "useRelativeToSource", null, 0, 1, ModelPersistence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getModelPersistence_UseRelativeToProject(), ecorePackage.getEBoolean(), "useRelativeToProject", null, 0, 1, ModelPersistence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModelPersistence_ModelPath(), this.getModelPathCodeBlock(), null, "modelPath", null, 0, 1, ModelPersistence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(correspondingModelElementDeleteEClass, CorrespondingModelElementDelete.class, "CorrespondingModelElementDelete", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(correspondingModelElementRetrieveEClass, CorrespondingModelElementRetrieve.class, "CorrespondingModelElementRetrieve", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCorrespondingModelElementRetrieve_RenamedModelFileName(), this.getModelPathCodeBlock(), null, "renamedModelFileName", null, 0, 1, CorrespondingModelElementRetrieve.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(correspondingModelElementRetrieveOrDeleteEClass, CorrespondingModelElementRetrieveOrDelete.class, "CorrespondingModelElementRetrieveOrDelete", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(correspondingModelElementSpecificationWithPreconditionEClass, CorrespondingModelElementSpecificationWithPrecondition.class, "CorrespondingModelElementSpecificationWithPrecondition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCorrespondingModelElementSpecificationWithPrecondition_Precondition(), this.getPreconditionCodeBlock(), null, "precondition", null, 0, 1, CorrespondingModelElementSpecificationWithPrecondition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(correspondingModelElementSpecificationEClass, CorrespondingModelElementSpecification.class, "CorrespondingModelElementSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCorrespondingModelElementSpecification_Name(), ecorePackage.getEString(), "name", null, 0, 1, CorrespondingModelElementSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCorrespondingModelElementSpecification_ElementType(), theMirBasePackage.getModelElement(), null, "elementType", null, 0, 1, CorrespondingModelElementSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCorrespondingModelElementSpecification_CorrespondenceSource(), this.getCorrespondingObjectCodeBlock(), null, "correspondenceSource", null, 0, 1, CorrespondingModelElementSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(arbitraryTargetMetamodelInstanceUpdateEClass, ArbitraryTargetMetamodelInstanceUpdate.class, "ArbitraryTargetMetamodelInstanceUpdate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getArbitraryTargetMetamodelInstanceUpdate_MetamodelReference(), theMirBasePackage.getMetamodelReference(), null, "metamodelReference", null, 0, 1, ArbitraryTargetMetamodelInstanceUpdate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(preconditionCodeBlockEClass, PreconditionCodeBlock.class, "PreconditionCodeBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(correspondingObjectCodeBlockEClass, CorrespondingObjectCodeBlock.class, "CorrespondingObjectCodeBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(modelPathCodeBlockEClass, ModelPathCodeBlock.class, "ModelPathCodeBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(executionCodeBlockEClass, ExecutionCodeBlock.class, "ExecutionCodeBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(codeBlockEClass, CodeBlock.class, "CodeBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCodeBlock_Code(), theXbasePackage.getXExpression(), null, "code", null, 0, 1, CodeBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(invariantViolationEventEClass, InvariantViolationEvent.class, "InvariantViolationEvent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInvariantViolationEvent_Violation(), ecorePackage.getEClass(), null, "violation", null, 0, 1, InvariantViolationEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(triggerEClass, Trigger.class, "Trigger", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTrigger_Precondition(), this.getPreconditionCodeBlock(), null, "precondition", null, 0, 1, Trigger.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelChangeEClass, ModelChange.class, "ModelChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(concreteModelElementChangeEClass, ConcreteModelElementChange.class, "ConcreteModelElementChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(atomicConcreteModelElementChangeEClass, AtomicConcreteModelElementChange.class, "AtomicConcreteModelElementChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(atomicRootObjectChangeEClass, AtomicRootObjectChange.class, "AtomicRootObjectChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAtomicRootObjectChange_ChangedElement(), theMirBasePackage.getModelElement(), null, "changedElement", null, 0, 1, AtomicRootObjectChange.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(atomicFeatureChangeEClass, AtomicFeatureChange.class, "AtomicFeatureChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAtomicFeatureChange_ChangedFeature(), theMirBasePackage.getFeatureOfElement(), null, "changedFeature", null, 0, 1, AtomicFeatureChange.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(atomicMultiValuedFeatureChangeEClass, AtomicMultiValuedFeatureChange.class, "AtomicMultiValuedFeatureChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(atomicSingleValuedFeatureChangeEClass, AtomicSingleValuedFeatureChange.class, "AtomicSingleValuedFeatureChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(arbitraryModelElementChangeEClass, ArbitraryModelElementChange.class, "ArbitraryModelElementChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getArbitraryModelElementChange_ChangedModel(), theMirBasePackage.getMetamodelReference(), null, "changedModel", null, 0, 1, ArbitraryModelElementChange.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(responseFileEClass, ResponseFile.class, "ResponseFile", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getResponseFile_NamespaceImports(), theXtypePackage.getXImportSection(), null, "namespaceImports", null, 0, 1, ResponseFile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getResponseFile_Responses(), this.getResponse(), null, "responses", null, 0, -1, ResponseFile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(insertRootChangeEClass, InsertRootChange.class, "InsertRootChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(removeRootChangeEClass, RemoveRootChange.class, "RemoveRootChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(multiValuedFeatureInsertChangeEClass, MultiValuedFeatureInsertChange.class, "MultiValuedFeatureInsertChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(multiValuedFeatureRemoveChangeEClass, MultiValuedFeatureRemoveChange.class, "MultiValuedFeatureRemoveChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(multiValuedFeaturePermuteChangeEClass, MultiValuedFeaturePermuteChange.class, "MultiValuedFeaturePermuteChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(singleValuedFeatureCreateEClass, SingleValuedFeatureCreate.class, "SingleValuedFeatureCreate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(singleValuedFeatureDeleteEClass, SingleValuedFeatureDelete.class, "SingleValuedFeatureDelete", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(singleValuedFeatureReplaceEClass, SingleValuedFeatureReplace.class, "SingleValuedFeatureReplace", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    // Create resource
    createResource(eNS_URI);
  }

} //ResponseLanguagePackageImpl
