<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="echange" nsURI="http://tools.vitruv/EChange/1.0" nsPrefix="echange">
  <eClassifiers xsi:type="ecore:EClass" name="EChange" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicEChange" abstract="true" eSuperTypes="#//EChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveEChange" abstract="true" eSuperTypes="#//AtomicEChange">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getNewValue" lowerBound="1">
      <eGenericType eTypeParameter="#//AdditiveEChange/T"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubtractiveEChange" abstract="true"
      eSuperTypes="#//AtomicEChange">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getOldValue" lowerBound="1">
      <eGenericType eTypeParameter="#//SubtractiveEChange/T"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectAddedEChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValue" lowerBound="1">
      <eGenericType eTypeParameter="#//EObjectAddedEChange/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCreate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="#//AdditiveEChange">
      <eTypeArguments eTypeParameter="#//EObjectAddedEChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectSubtractedEChange" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldValue" lowerBound="1">
      <eGenericType eTypeParameter="#//EObjectSubtractedEChange/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDelete" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="#//SubtractiveEChange">
      <eTypeArguments eTypeParameter="#//EObjectSubtractedEChange/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eSubpackages name="feature" nsURI="http://tools.vitruv/EChange/Feature/1.0" nsPrefix="feature">
    <eClassifiers xsi:type="ecore:EClass" name="FeatureEChange" abstract="true" eSuperTypes="#//AtomicEChange">
      <eTypeParameters name="A">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="F">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="affectedFeature" lowerBound="1">
        <eGenericType eTypeParameter="#//feature/FeatureEChange/F"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="affectedEObject" lowerBound="1">
        <eGenericType eTypeParameter="#//feature/FeatureEChange/A"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UpdateMultiValuedFeatureEChange" abstract="true">
      <eTypeParameters name="A">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="F">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//feature/FeatureEChange">
        <eTypeArguments eTypeParameter="#//feature/UpdateMultiValuedFeatureEChange/A"/>
        <eTypeArguments eTypeParameter="#//feature/UpdateMultiValuedFeatureEChange/F"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UpdateSingleValuedFeatureEChange"
        abstract="true">
      <eTypeParameters name="A">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="F">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//feature/FeatureEChange">
        <eTypeArguments eTypeParameter="#//feature/UpdateSingleValuedFeatureEChange/A"/>
        <eTypeArguments eTypeParameter="#//feature/UpdateSingleValuedFeatureEChange/F"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eSubpackages name="single" nsURI="http://tools.vitruv/EChange/Feature/Single/1.0"
        nsPrefix="single">
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceSingleValuedFeatureEChange"
          abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="F">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eOperations name="isFromNonDefaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return !java.util.Objects.equals(getOldValue(), getAffectedFeature().getDefaultValue());"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="isToNonDefaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return !java.util.Objects.equals(getNewValue(), getAffectedFeature().getDefaultValue());"/>
          </eAnnotations>
        </eOperations>
        <eGenericSuperTypes eClassifier="#//feature/UpdateSingleValuedFeatureEChange">
          <eTypeArguments eTypeParameter="#//feature/single/ReplaceSingleValuedFeatureEChange/A"/>
          <eTypeArguments eTypeParameter="#//feature/single/ReplaceSingleValuedFeatureEChange/F"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//AdditiveEChange">
          <eTypeArguments eTypeParameter="#//feature/single/ReplaceSingleValuedFeatureEChange/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//SubtractiveEChange">
          <eTypeArguments eTypeParameter="#//feature/single/ReplaceSingleValuedFeatureEChange/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="list" nsURI="http://tools.vitruv/EChange/Feature/List/1.0"
        nsPrefix="list">
      <eClassifiers xsi:type="ecore:EClass" name="UpdateSingleListEntryEChange" abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="F">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
        </eTypeParameters>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
        <eGenericSuperTypes eClassifier="#//feature/UpdateMultiValuedFeatureEChange">
          <eTypeArguments eTypeParameter="#//feature/list/UpdateSingleListEntryEChange/A"/>
          <eTypeArguments eTypeParameter="#//feature/list/UpdateSingleListEntryEChange/F"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InsertInListEChange" abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="F">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/UpdateSingleListEntryEChange">
          <eTypeArguments eTypeParameter="#//feature/list/InsertInListEChange/A"/>
          <eTypeArguments eTypeParameter="#//feature/list/InsertInListEChange/F"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//AdditiveEChange">
          <eTypeArguments eTypeParameter="#//feature/list/InsertInListEChange/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RemoveFromListEChange" abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="F">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/UpdateSingleListEntryEChange">
          <eTypeArguments eTypeParameter="#//feature/list/RemoveFromListEChange/A"/>
          <eTypeArguments eTypeParameter="#//feature/list/RemoveFromListEChange/F"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//SubtractiveEChange">
          <eTypeArguments eTypeParameter="#//feature/list/RemoveFromListEChange/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PermuteListEChange" abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="F">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
        </eTypeParameters>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="newIndicesForElementsAtOldIndices"
            lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eGenericSuperTypes eClassifier="#//feature/UpdateMultiValuedFeatureEChange">
          <eTypeArguments eTypeParameter="#//feature/list/PermuteListEChange/A"/>
          <eTypeArguments eTypeParameter="#//feature/list/PermuteListEChange/F"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="attribute" nsURI="http://tools.vitruv/EChange/Feature/Attribute/1.0"
        nsPrefix="attribute">
      <eClassifiers xsi:type="ecore:EClass" name="UpdateAttributeEChange" abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/FeatureEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/UpdateAttributeEChange/A"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AdditiveAttributeEChange" abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" lowerBound="1">
          <eGenericType eTypeParameter="#//feature/attribute/AdditiveAttributeEChange/T"/>
        </eStructuralFeatures>
        <eGenericSuperTypes eClassifier="#//AdditiveEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/AdditiveAttributeEChange/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateAttributeEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/AdditiveAttributeEChange/A"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SubtractiveAttributeEChange" abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldValue" lowerBound="1">
          <eGenericType eTypeParameter="#//feature/attribute/SubtractiveAttributeEChange/T"/>
        </eStructuralFeatures>
        <eGenericSuperTypes eClassifier="#//SubtractiveEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/SubtractiveAttributeEChange/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateAttributeEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/SubtractiveAttributeEChange/A"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InsertEAttributeValue">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/InsertInListEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/InsertEAttributeValue/A"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
          <eTypeArguments eTypeParameter="#//feature/attribute/InsertEAttributeValue/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/AdditiveAttributeEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/InsertEAttributeValue/A"/>
          <eTypeArguments eTypeParameter="#//feature/attribute/InsertEAttributeValue/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RemoveEAttributeValue">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/RemoveFromListEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/RemoveEAttributeValue/A"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
          <eTypeArguments eTypeParameter="#//feature/attribute/RemoveEAttributeValue/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/SubtractiveAttributeEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/RemoveEAttributeValue/A"/>
          <eTypeArguments eTypeParameter="#//feature/attribute/RemoveEAttributeValue/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PermuteEAttributeValues">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/PermuteListEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/PermuteEAttributeValues/A"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/UpdateAttributeEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/PermuteEAttributeValues/A"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceSingleValuedEAttribute">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/attribute/AdditiveAttributeEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/A"/>
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/attribute/SubtractiveAttributeEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/A"/>
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/single/ReplaceSingleValuedFeatureEChange">
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/A"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
          <eTypeArguments eTypeParameter="#//feature/attribute/ReplaceSingleValuedEAttribute/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="reference" nsURI="http://tools.vitruv/EChange/Feature/Reference/Containment/1.0"
        nsPrefix="reference">
      <eClassifiers xsi:type="ecore:EClass" name="UpdateReferenceEChange" abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eOperations name="isContainment" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="body" value="return getAffectedFeature().isContainment();"/>
          </eAnnotations>
        </eOperations>
        <eGenericSuperTypes eClassifier="#//feature/FeatureEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/UpdateReferenceEChange/A"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AdditiveReferenceEChange" abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//EObjectAddedEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/AdditiveReferenceEChange/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateReferenceEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/AdditiveReferenceEChange/A"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SubtractiveReferenceEChange" abstract="true">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//EObjectSubtractedEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/SubtractiveReferenceEChange/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateReferenceEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/SubtractiveReferenceEChange/A"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InsertEReference">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/InsertInListEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/InsertEReference/A"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
          <eTypeArguments eTypeParameter="#//feature/reference/InsertEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/AdditiveReferenceEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/InsertEReference/A"/>
          <eTypeArguments eTypeParameter="#//feature/reference/InsertEReference/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RemoveEReference">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/RemoveFromListEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/RemoveEReference/A"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
          <eTypeArguments eTypeParameter="#//feature/reference/RemoveEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/SubtractiveReferenceEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/RemoveEReference/A"/>
          <eTypeArguments eTypeParameter="#//feature/reference/RemoveEReference/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PermuteEReferences">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/list/PermuteListEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/PermuteEReferences/A"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/UpdateReferenceEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/PermuteEReferences/A"/>
        </eGenericSuperTypes>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReplaceSingleValuedEReference">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
        </eTypeParameters>
        <eGenericSuperTypes eClassifier="#//feature/reference/AdditiveReferenceEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceSingleValuedEReference/A"/>
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceSingleValuedEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/reference/SubtractiveReferenceEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceSingleValuedEReference/A"/>
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceSingleValuedEReference/T"/>
        </eGenericSuperTypes>
        <eGenericSuperTypes eClassifier="#//feature/single/ReplaceSingleValuedFeatureEChange">
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceSingleValuedEReference/A"/>
          <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
          <eTypeArguments eTypeParameter="#//feature/reference/ReplaceSingleValuedEReference/T"/>
        </eGenericSuperTypes>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="root" nsURI="http://tools.vitruv/EChange/Root/1.0" nsPrefix="root">
    <eClassifiers xsi:type="ecore:EClass" name="RootEChange" abstract="true" eSuperTypes="#//AtomicEChange">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InsertRootEObject">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//root/RootEChange"/>
      <eGenericSuperTypes eClassifier="#//EObjectAddedEChange">
        <eTypeArguments eTypeParameter="#//root/InsertRootEObject/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RemoveRootEObject">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="#//root/RootEChange"/>
      <eGenericSuperTypes eClassifier="#//EObjectSubtractedEChange">
        <eTypeArguments eTypeParameter="#//root/RemoveRootEObject/T"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="compound" nsURI="http://tools.vitruv/EChange/Compound/1.0" nsPrefix="compound">
    <eClassifiers xsi:type="ecore:EClass" name="CompoundEChange" abstract="true" eSuperTypes="#//EChange">
      <eOperations name="getAtomicChanges" lowerBound="1" upperBound="-1" eType="#//AtomicEChange"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MoveEObject" eSuperTypes="#//compound/CompoundEChange">
      <eTypeParameters name="A">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="B">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eOperations name="getAtomicChanges" lowerBound="1" upperBound="-1" eType="#//AtomicEChange">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="org.eclipse.emf.common.util.BasicEList&lt;AtomicEChange> list = new org.eclipse.emf.common.util.BasicEList&lt;AtomicEChange>();&#xD;&#xA;UpdateReferenceEChange&lt;A> subWhereChange = getSubtractWhereChange();&#xD;&#xA;if (subWhereChange != null) {&#xD;&#xA;    list.add(subWhereChange);&#xD;&#xA;}&#xD;&#xA;list.add(getSubtractWhatChange());&#xD;&#xA;UpdateReferenceEChange&lt;B> addWhereChange = getAddWhereChange();&#xD;&#xA;if (addWhereChange != null) {&#xD;&#xA;    list.add(addWhereChange);&#xD;&#xA;}&#xD;&#xA;list.add(getAddWhatChange());&#xD;&#xA;return list;"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subtractWhereChange">
        <eGenericType eClassifier="#//feature/reference/UpdateReferenceEChange">
          <eTypeArguments eTypeParameter="#//compound/MoveEObject/A"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subtractWhatChange" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//EObjectSubtractedEChange">
          <eTypeArguments eTypeParameter="#//compound/MoveEObject/T"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="addWhereChange">
        <eGenericType eClassifier="#//feature/reference/UpdateReferenceEChange">
          <eTypeArguments eTypeParameter="#//compound/MoveEObject/B"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="addWhatChange" lowerBound="1"
          containment="true">
        <eGenericType eClassifier="#//EObjectAddedEChange">
          <eTypeArguments eTypeParameter="#//compound/MoveEObject/T"/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExplicitUnsetEFeature" eSuperTypes="#//compound/CompoundEChange">
      <eTypeParameters name="A">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="F">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eTypeParameters>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eTypeParameters>
      <eTypeParameters name="S">
        <eBounds eClassifier="#//feature/FeatureEChange">
          <eTypeArguments eTypeParameter="#//compound/ExplicitUnsetEFeature/A"/>
          <eTypeArguments eTypeParameter="#//compound/ExplicitUnsetEFeature/F"/>
        </eBounds>
        <eBounds eClassifier="#//SubtractiveEChange">
          <eTypeArguments eTypeParameter="#//compound/ExplicitUnsetEFeature/T"/>
        </eBounds>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subtractiveChanges" lowerBound="1"
          upperBound="-1" unsettable="true">
        <eGenericType eTypeParameter="#//compound/ExplicitUnsetEFeature/S"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReplaceInEList" eSuperTypes="#//compound/CompoundEChange">
      <eTypeParameters name="A">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="F">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
      </eTypeParameters>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eTypeParameters>
      <eTypeParameters name="R">
        <eBounds eClassifier="#//feature/list/RemoveFromListEChange">
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/A"/>
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/F"/>
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/T"/>
        </eBounds>
        <eBounds eClassifier="#//feature/FeatureEChange">
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/A"/>
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/F"/>
        </eBounds>
        <eBounds eClassifier="#//SubtractiveEChange">
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/T"/>
        </eBounds>
      </eTypeParameters>
      <eTypeParameters name="I">
        <eBounds eClassifier="#//feature/list/InsertInListEChange">
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/A"/>
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/F"/>
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/T"/>
        </eBounds>
        <eBounds eClassifier="#//feature/FeatureEChange">
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/A"/>
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/F"/>
        </eBounds>
        <eBounds eClassifier="#//AdditiveEChange">
          <eTypeArguments eTypeParameter="#//compound/ReplaceInEList/T"/>
        </eBounds>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="removeChange" lowerBound="1"
          containment="true">
        <eGenericType eTypeParameter="#//compound/ReplaceInEList/R"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="insertChange" lowerBound="1"
          containment="true">
        <eGenericType eTypeParameter="#//compound/ReplaceInEList/I"/>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
