<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vavemodel" nsURI="http://tools.vitruv/Vave/1.0" nsPrefix="vavemodel">
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
        eType="#//CrossTreeConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" upperBound="-1"
        eType="#//Mapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deltamodule" upperBound="-1"
        eType="#//DeltaModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemrevision" upperBound="-1"
        eType="#//SystemRevision" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" upperBound="-1"
        eType="#//Configuration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//FeatureOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="treeconstraint" upperBound="-1"
        eType="#//TreeConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featurerevision" upperBound="-1"
        eType="#//FeatureRevision" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrossTreeConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        containment="true">
      <eGenericType eClassifier="#//Expression">
        <eTypeArguments eClassifier="#//FeatureOption"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TreeConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//GroupType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        upperBound="-1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GroupType">
    <eLiterals name="XOR"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="XORNONE" value="2"/>
    <eLiterals name="ORNONE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureRevision" eSuperTypes="#//Revision #//FeatureOption"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeltaModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deltamodule" upperBound="-1"
        eType="#//DeltaModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="change" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../tools.vitruv.framework.change.echange/metamodel/echange.ecore#//EChange"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Option"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" lowerBound="1">
      <eGenericType eTypeParameter="#//Variable/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Expression">
      <eTypeArguments eTypeParameter="#//Variable/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Option"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//Term">
      <eTypeArguments eTypeParameter="#//Expression/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Term" abstract="true" interface="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Option"/>
    </eTypeParameters>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Option"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" lowerBound="2" upperBound="2"
        containment="true">
      <eGenericType eClassifier="#//Term">
        <eTypeArguments eTypeParameter="#//BinaryExpression/T"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Expression">
      <eTypeArguments eTypeParameter="#//BinaryExpression/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Option"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" lowerBound="1" containment="true">
      <eGenericType eClassifier="#//Term">
        <eTypeArguments eTypeParameter="#//UnaryExpression/T"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Expression">
      <eTypeArguments eTypeParameter="#//UnaryExpression/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implication">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Option"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//BinaryExpression">
      <eTypeArguments eTypeParameter="#//Implication/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Disjunction">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Option"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//BinaryExpression">
      <eTypeArguments eTypeParameter="#//Disjunction/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equivalence">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Option"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//BinaryExpression">
      <eTypeArguments eTypeParameter="#//Equivalence/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conjunction">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Option"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//BinaryExpression">
      <eTypeArguments eTypeParameter="#//Conjunction/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Option"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//UnaryExpression">
      <eTypeArguments eTypeParameter="#//Not/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Option" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deltamodule" lowerBound="1"
        upperBound="-1" eType="#//DeltaModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        containment="true">
      <eGenericType eClassifier="#//Expression">
        <eTypeArguments eClassifier="#//Option"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Revision" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="successors" upperBound="-1"
        eType="#//Revision" eOpposite="#//Revision/predecessors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessors" upperBound="-1"
        eType="#//Revision" eOpposite="#//Revision/successors"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revisionID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureOption" abstract="true" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemRevision" eSuperTypes="#//Option #//Revision">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enablesoptions" upperBound="-1"
        eType="#//FeatureOption"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enablesconstraints" upperBound="-1"
        eType="#//Constraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" upperBound="-1"
        eType="#//Option"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="True">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Option"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//Expression">
      <eTypeArguments eTypeParameter="#//True/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="False">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Option"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//Expression">
      <eTypeArguments eTypeParameter="#//False/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
