/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.response.responseLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concrete Model Element Change</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.response.responseLanguage.ResponseLanguagePackage#getConcreteModelElementChange()
 * @model
 * @generated
 */
public interface ConcreteModelElementChange extends ModelChange
{
} // ConcreteModelElementChange
