/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.response.responseLanguage;

import tools.vitruv.dsls.mirbase.mirBase.ModelElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.response.responseLanguage.CreateElement#getElement <em>Element</em>}</li>
 *   <li>{@link tools.vitruv.dsls.response.responseLanguage.CreateElement#getInitializationBlock <em>Initialization Block</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.response.responseLanguage.ResponseLanguagePackage#getCreateElement()
 * @model
 * @generated
 */
public interface CreateElement extends EffectStatement
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference.
   * @see #setElement(ModelElement)
   * @see tools.vitruv.dsls.response.responseLanguage.ResponseLanguagePackage#getCreateElement_Element()
   * @model containment="true"
   * @generated
   */
  ModelElement getElement();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.response.responseLanguage.CreateElement#getElement <em>Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' containment reference.
   * @see #getElement()
   * @generated
   */
  void setElement(ModelElement value);

  /**
   * Returns the value of the '<em><b>Initialization Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Initialization Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initialization Block</em>' containment reference.
   * @see #setInitializationBlock(ExecutionCodeBlock)
   * @see tools.vitruv.dsls.response.responseLanguage.ResponseLanguagePackage#getCreateElement_InitializationBlock()
   * @model containment="true"
   * @generated
   */
  ExecutionCodeBlock getInitializationBlock();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.response.responseLanguage.CreateElement#getInitializationBlock <em>Initialization Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initialization Block</em>' containment reference.
   * @see #getInitializationBlock()
   * @generated
   */
  void setInitializationBlock(ExecutionCodeBlock value);

} // CreateElement
