/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.response.responseLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.xtype.XImportSection;

import tools.vitruv.dsls.mirbase.mirBase.MirBaseFile;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reactions File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.response.responseLanguage.ReactionsFile#getNamespaceImports <em>Namespace Imports</em>}</li>
 *   <li>{@link tools.vitruv.dsls.response.responseLanguage.ReactionsFile#getReactionsSegments <em>Reactions Segments</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.response.responseLanguage.ResponseLanguagePackage#getReactionsFile()
 * @model
 * @generated
 */
public interface ReactionsFile extends MirBaseFile
{
  /**
   * Returns the value of the '<em><b>Namespace Imports</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Namespace Imports</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Namespace Imports</em>' containment reference.
   * @see #setNamespaceImports(XImportSection)
   * @see tools.vitruv.dsls.response.responseLanguage.ResponseLanguagePackage#getReactionsFile_NamespaceImports()
   * @model containment="true"
   * @generated
   */
  XImportSection getNamespaceImports();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.response.responseLanguage.ReactionsFile#getNamespaceImports <em>Namespace Imports</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Namespace Imports</em>' containment reference.
   * @see #getNamespaceImports()
   * @generated
   */
  void setNamespaceImports(XImportSection value);

  /**
   * Returns the value of the '<em><b>Reactions Segments</b></em>' containment reference list.
   * The list contents are of type {@link tools.vitruv.dsls.response.responseLanguage.ReactionsSegment}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reactions Segments</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reactions Segments</em>' containment reference list.
   * @see tools.vitruv.dsls.response.responseLanguage.ResponseLanguagePackage#getReactionsFile_ReactionsSegments()
   * @model containment="true"
   * @generated
   */
  EList<ReactionsSegment> getReactionsSegments();

} // ReactionsFile
