/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.response.responseLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see tools.vitruv.dsls.response.responseLanguage.ResponseLanguagePackage
 * @generated
 */
public interface ResponseLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ResponseLanguageFactory eINSTANCE = tools.vitruv.dsls.response.responseLanguage.impl.ResponseLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Reactions File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reactions File</em>'.
   * @generated
   */
  ReactionsFile createReactionsFile();

  /**
   * Returns a new object of class '<em>Reactions Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reactions Segment</em>'.
   * @generated
   */
  ReactionsSegment createReactionsSegment();

  /**
   * Returns a new object of class '<em>Reaction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reaction</em>'.
   * @generated
   */
  Reaction createReaction();

  /**
   * Returns a new object of class '<em>Response Reaction Routine Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Response Reaction Routine Call</em>'.
   * @generated
   */
  ResponseReactionRoutineCall createResponseReactionRoutineCall();

  /**
   * Returns a new object of class '<em>Invariant Violation Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Invariant Violation Event</em>'.
   * @generated
   */
  InvariantViolationEvent createInvariantViolationEvent();

  /**
   * Returns a new object of class '<em>Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trigger</em>'.
   * @generated
   */
  Trigger createTrigger();

  /**
   * Returns a new object of class '<em>Model Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model Change</em>'.
   * @generated
   */
  ModelChange createModelChange();

  /**
   * Returns a new object of class '<em>Concrete Model Element Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Concrete Model Element Change</em>'.
   * @generated
   */
  ConcreteModelElementChange createConcreteModelElementChange();

  /**
   * Returns a new object of class '<em>Atomic Concrete Model Element Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Atomic Concrete Model Element Change</em>'.
   * @generated
   */
  AtomicConcreteModelElementChange createAtomicConcreteModelElementChange();

  /**
   * Returns a new object of class '<em>Atomic Root Object Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Atomic Root Object Change</em>'.
   * @generated
   */
  AtomicRootObjectChange createAtomicRootObjectChange();

  /**
   * Returns a new object of class '<em>Atomic Feature Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Atomic Feature Change</em>'.
   * @generated
   */
  AtomicFeatureChange createAtomicFeatureChange();

  /**
   * Returns a new object of class '<em>Atomic Multi Valued Feature Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Atomic Multi Valued Feature Change</em>'.
   * @generated
   */
  AtomicMultiValuedFeatureChange createAtomicMultiValuedFeatureChange();

  /**
   * Returns a new object of class '<em>Atomic Single Valued Feature Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Atomic Single Valued Feature Change</em>'.
   * @generated
   */
  AtomicSingleValuedFeatureChange createAtomicSingleValuedFeatureChange();

  /**
   * Returns a new object of class '<em>Arbitrary Model Element Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arbitrary Model Element Change</em>'.
   * @generated
   */
  ArbitraryModelElementChange createArbitraryModelElementChange();

  /**
   * Returns a new object of class '<em>Routine</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Routine</em>'.
   * @generated
   */
  Routine createRoutine();

  /**
   * Returns a new object of class '<em>Routine Input</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Routine Input</em>'.
   * @generated
   */
  RoutineInput createRoutineInput();

  /**
   * Returns a new object of class '<em>Matcher</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Matcher</em>'.
   * @generated
   */
  Matcher createMatcher();

  /**
   * Returns a new object of class '<em>Matcher Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Matcher Statement</em>'.
   * @generated
   */
  MatcherStatement createMatcherStatement();

  /**
   * Returns a new object of class '<em>Retrieve Model Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Retrieve Model Element</em>'.
   * @generated
   */
  RetrieveModelElement createRetrieveModelElement();

  /**
   * Returns a new object of class '<em>Matcher Check Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Matcher Check Statement</em>'.
   * @generated
   */
  MatcherCheckStatement createMatcherCheckStatement();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>Routine Call Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Routine Call Statement</em>'.
   * @generated
   */
  RoutineCallStatement createRoutineCallStatement();

  /**
   * Returns a new object of class '<em>Action Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action Statement</em>'.
   * @generated
   */
  ActionStatement createActionStatement();

  /**
   * Returns a new object of class '<em>Create Model Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Create Model Element</em>'.
   * @generated
   */
  CreateModelElement createCreateModelElement();

  /**
   * Returns a new object of class '<em>Delete Model Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delete Model Element</em>'.
   * @generated
   */
  DeleteModelElement createDeleteModelElement();

  /**
   * Returns a new object of class '<em>Update Model Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Update Model Element</em>'.
   * @generated
   */
  UpdateModelElement createUpdateModelElement();

  /**
   * Returns a new object of class '<em>Create Correspondence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Create Correspondence</em>'.
   * @generated
   */
  CreateCorrespondence createCreateCorrespondence();

  /**
   * Returns a new object of class '<em>Remove Correspondence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Remove Correspondence</em>'.
   * @generated
   */
  RemoveCorrespondence createRemoveCorrespondence();

  /**
   * Returns a new object of class '<em>Code Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Code Block</em>'.
   * @generated
   */
  CodeBlock createCodeBlock();

  /**
   * Returns a new object of class '<em>Execute Action Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Execute Action Block</em>'.
   * @generated
   */
  ExecuteActionBlock createExecuteActionBlock();

  /**
   * Returns a new object of class '<em>Routine Call Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Routine Call Block</em>'.
   * @generated
   */
  RoutineCallBlock createRoutineCallBlock();

  /**
   * Returns a new object of class '<em>Taggable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Taggable</em>'.
   * @generated
   */
  Taggable createTaggable();

  /**
   * Returns a new object of class '<em>Existing Element Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Existing Element Reference</em>'.
   * @generated
   */
  ExistingElementReference createExistingElementReference();

  /**
   * Returns a new object of class '<em>Tag Code Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tag Code Block</em>'.
   * @generated
   */
  TagCodeBlock createTagCodeBlock();

  /**
   * Returns a new object of class '<em>Precondition Code Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Precondition Code Block</em>'.
   * @generated
   */
  PreconditionCodeBlock createPreconditionCodeBlock();

  /**
   * Returns a new object of class '<em>Corresponding Object Code Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Corresponding Object Code Block</em>'.
   * @generated
   */
  CorrespondingObjectCodeBlock createCorrespondingObjectCodeBlock();

  /**
   * Returns a new object of class '<em>Execution Code Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Execution Code Block</em>'.
   * @generated
   */
  ExecutionCodeBlock createExecutionCodeBlock();

  /**
   * Returns a new object of class '<em>Return Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Return Statement</em>'.
   * @generated
   */
  ReturnStatement createReturnStatement();

  /**
   * Returns a new object of class '<em>Insert Root Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Insert Root Change</em>'.
   * @generated
   */
  InsertRootChange createInsertRootChange();

  /**
   * Returns a new object of class '<em>Remove Root Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Remove Root Change</em>'.
   * @generated
   */
  RemoveRootChange createRemoveRootChange();

  /**
   * Returns a new object of class '<em>Multi Valued Feature Insert Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multi Valued Feature Insert Change</em>'.
   * @generated
   */
  MultiValuedFeatureInsertChange createMultiValuedFeatureInsertChange();

  /**
   * Returns a new object of class '<em>Multi Valued Feature Remove Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multi Valued Feature Remove Change</em>'.
   * @generated
   */
  MultiValuedFeatureRemoveChange createMultiValuedFeatureRemoveChange();

  /**
   * Returns a new object of class '<em>Multi Valued Feature Permute Change</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multi Valued Feature Permute Change</em>'.
   * @generated
   */
  MultiValuedFeaturePermuteChange createMultiValuedFeaturePermuteChange();

  /**
   * Returns a new object of class '<em>Single Valued Feature Replace</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Valued Feature Replace</em>'.
   * @generated
   */
  SingleValuedFeatureReplace createSingleValuedFeatureReplace();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ResponseLanguagePackage getResponseLanguagePackage();

} //ResponseLanguageFactory
