/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.response.responseLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Routine Call Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.response.responseLanguage.ResponseLanguagePackage#getRoutineCallStatement()
 * @model
 * @generated
 */
public interface RoutineCallStatement extends RoutineCallBlock, CodeBlock, EffectStatement
{
} // RoutineCallStatement
