/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.mirbase.mirBase;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dummy Entry Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.mirbase.mirBase.MirBasePackage#getDummyEntryRule()
 * @model
 * @generated
 */
public interface DummyEntryRule extends MirBaseFile
{
} // DummyEntryRule
