/**
 * generated by Xtext 2.9.2
 */
package tools.vitruvius.dsls.mirbase.mirBase;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature Of Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruvius.dsls.mirbase.mirBase.FeatureOfElement#getElement <em>Element</em>}</li>
 *   <li>{@link tools.vitruvius.dsls.mirbase.mirBase.FeatureOfElement#getFeature <em>Feature</em>}</li>
 * </ul>
 *
 * @see tools.vitruvius.dsls.mirbase.mirBase.MirBasePackage#getFeatureOfElement()
 * @model
 * @generated
 */
public interface FeatureOfElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' reference.
   * @see #setElement(EClass)
   * @see tools.vitruvius.dsls.mirbase.mirBase.MirBasePackage#getFeatureOfElement_Element()
   * @model
   * @generated
   */
  EClass getElement();

  /**
   * Sets the value of the '{@link tools.vitruvius.dsls.mirbase.mirBase.FeatureOfElement#getElement <em>Element</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' reference.
   * @see #getElement()
   * @generated
   */
  void setElement(EClass value);

  /**
   * Returns the value of the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature</em>' reference.
   * @see #setFeature(EStructuralFeature)
   * @see tools.vitruvius.dsls.mirbase.mirBase.MirBasePackage#getFeatureOfElement_Feature()
   * @model
   * @generated
   */
  EStructuralFeature getFeature();

  /**
   * Sets the value of the '{@link tools.vitruvius.dsls.mirbase.mirBase.FeatureOfElement#getFeature <em>Feature</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature</em>' reference.
   * @see #getFeature()
   * @generated
   */
  void setFeature(EStructuralFeature value);

} // FeatureOfElement
