package edu.kit.ipd.sdq.vitruvius.dsls.mapping.testframework.tests

import edu.kit.ipd.sdq.vitruvius.framework.change2commandtransformingprovider.AbstractChange2CommandTransformingProviding

abstract class MappingLanguageTestChange2CommandTransformingProvidingImpl extends AbstractChange2CommandTransformingProviding {
	
}