/*
 * generated by Xtext
 */
package edu.kit.ipd.sdq.vitruvius.domains.jml.language;

import edu.kit.ipd.sdq.vitruvius.domains.jml.language.JMLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without equinox extension registry
 */
public class JMLStandaloneSetup extends JMLStandaloneSetupGenerated {

    /**
     * Performs the necessary initialization for standalone usage.
     */
    public static void doSetup() {
        new JMLStandaloneSetup().createInjectorAndDoEMFRegistration();
    }

}
