package tools.vitruv.applications.familiespersons.families2persons

import mir.reactions.reactionsFamiliesToPersons.familiesToPersons.ChangePropagationSpecificationFamiliesToPersons

class FamiliesToPersonsChangePropagationSpecification extends ChangePropagationSpecificationFamiliesToPersons {

}