<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="echange" nsURI="http://tools.vitruv/EChange/1.0" nsPrefix="echange">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="modelName" value="Change"/>
    <details key="prefix" value="EChange"/>
    <details key="basePackage" value="tools.vitruv.framework.change"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EChange" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="*&#xA;Abstract change, which can be applied forward or backward, after it was resolved to a specific instance of a model."/>
    </eAnnotations>
    <eOperations name="isResolved" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return tools.vitruv.framework.change.echange.resolve.ResolutionChecker.isResolved(this);"/>
        <details key="documentation" value="*&#xA;Returns if all IDs in this chang eare resolved to {@link EObjects}.&#xA;Needs to be true to apply the change.&#xA;@return&#x9;Whether elements in this change are resolved or not."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getInvolvedEObjects" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="org.eclipse.emf.common.util.EList&lt;EObject> result = new org.eclipse.emf.common.util.BasicEList&lt;EObject>();&#xD;&#xA;for (EObject involvedEObject : tools.vitruv.framework.change.echange.EChangeInformationExtractor.getInvolvedEObjects(this)) {&#xD;&#xA;&#x9;result.add(involvedEObject);&#xD;&#xA;}&#xD;&#xA;return result;"/>
        <details key="documentation" value="*&#xA;Returns the objects involved in this change, which includes all affected objects, new values and old values.&#xA;@return&#x9;All elements involved in this change."/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicEChange" abstract="true" eSuperTypes="#//EChange">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="*&#xA;Abstract EChange which sub changes can only be applied together."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditiveEChange" abstract="true" eSuperTypes="#//AtomicEChange">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="*&#xA;Abstract EChange which adds a new value, like an EObject or primitive type."/>
    </eAnnotations>
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getNewValue" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Get the added value.&#xA;@return The newly added value."/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//AdditiveEChange/T"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubtractiveEChange" abstract="true"
      eSuperTypes="#//AtomicEChange">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="*&#xA;Abstract EChange which removes an existing value, like an EObject or primitive type."/>
    </eAnnotations>
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getOldValue" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="*&#xA;Get the removed value.&#xA;@return The value which will be removed."/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//SubtractiveEChange/T"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
