<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="id" nsURI="http://tools.vitruv/EChange/Id/1.0" nsPrefix="id">
  <eClassifiers xsi:type="ecore:EClass" name="IdEObjectRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="idToEObject" upperBound="-1"
        eType="#//IdToEObjectMapEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObjectToId" upperBound="-1"
        eType="#//EObjectToIdMapEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdToEObjectMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="#//Id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectToIdMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Id"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Id" instanceClassName="java.lang.String"/>
</ecore:EPackage>
