package edu.kit.ipd.sdq.vitruvius.framework.mir.executor.interfaces;

import java.util.List;

import org.eclipse.emf.ecore.EObject;

import edu.kit.ipd.sdq.vitruvius.framework.contracts.datatypes.CorrespondenceInstance;
import edu.kit.ipd.sdq.vitruvius.framework.contracts.datatypes.EMFChangeResult;
import edu.kit.ipd.sdq.vitruvius.framework.meta.change.EChange;
import edu.kit.ipd.sdq.vitruvius.framework.util.datatypes.Pair;

/**
 * Represents a MIR mapping. Concrete implementations are generated by
 * {@link MIRCodeGenerator}. A MIR mapping is 
 * @author Dominik Werle
 *
 */
public interface MIRMapping {
	/**
	 * Returns <code>true</code> if the mapping matches the given eObject.
	 * @param eObject the object to check
	 * @param correspondenceInstance the correspondence instance for the current context
	 * @return true if the mapping applies to the given object
	 */
	public boolean doesMatch(EObject eObject, CorrespondenceInstance correspondenceInstance);
	
	public Pair<List<String>, EMFChangeResult> applyEChange(EChange eChange, CorrespondenceInstance correspondenceInstance);
}
