package edu.kit.ipd.sdq.vitruvius.framework.mir.executor.interfaces;

import edu.kit.ipd.sdq.vitruvius.framework.contracts.datatypes.CorrespondenceInstance;
import edu.kit.ipd.sdq.vitruvius.framework.contracts.datatypes.EMFChangeResult;
import edu.kit.ipd.sdq.vitruvius.framework.meta.change.EChange;

/**
 * Represents a MIR mapping. Concrete implementations are generated by
 * {@link MIRCodeGenerator}. A MIR mapping is 
 * @author Dominik Werle
 *
 */
public interface MIRMapping {
	/**
	 * Applies the mapping.
	 * @param eChange
	 * @param correspondenceInstance
	 * @param modelInformationProvider
	 * @return the resulting change
	 */
	public EMFChangeResult applyEChange(EChange eChange, CorrespondenceInstance correspondenceInstance, MIRModelInformationProvider modelInformationProvider);
}
