/*
 * generated by Xtext 2.9.0
 */
package edu.kit.ipd.sdq.vitruvius.dsls.response.serializer


class ResponseLanguageSyntacticSequencer extends AbstractResponseLanguageSyntacticSequencer {
}
