package tools.vitruv.applications.demo.insurancepersons.persons2insurance

class PersonsToInsuranceChangePropagationSpecification extends mir.reactions.personsToInsurance.PersonsToInsuranceChangePropagationSpecification {
}
