<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="advancedfeatures" nsURI="http://example.com/advancedfeatures"
    nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="FeatureMapContaining"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceListContaining">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nonContainmentRefList"
        upperBound="-1" eType="#//DummyData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DummyData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dummyData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DummyDataContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dummyDataObjs" upperBound="-1"
        eType="#//DummyData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeListContaining">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrList" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureMapContaining" eType="#//FeatureMapContaining"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceListContaining"
        eType="#//ReferenceListContaining" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dummyDataContainerContaining"
        eType="#//DummyDataContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeListContaining"
        eType="#//AttributeListContaining" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
