package a.b.c;

class ForallExpression {

    public static short arrayCopy(byte[] src, short  srcOff,
                                  byte[] dest, short  destOff, short  length)
                                  throws TransactionException, NullPointerException, ArrayIndexOutOfBoundsException
                                  {
                                  	return 0;
                                  }

}