package mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests;

import tools.vitruvius.extensions.dslsruntime.response.AbstractResponseExecutor;
import tools.vitruvius.framework.userinteraction.UserInteracting;

@SuppressWarnings("all")
public class ExecutorAllElementTypesToAllElementTypes extends AbstractResponseExecutor {
  public ExecutorAllElementTypesToAllElementTypes(final UserInteracting userInteracting) {
    super(userInteracting);
  }
  
  protected void setup() {
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.UpdateSingleValuedEAttributeResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.UpdateSingleValuedEAttributeResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.ReplaceNonRootIdResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.ReplaceNonRootIdResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.CreateNonRootEObjectInListResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.CreateNonRootEObjectInListResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.DeleteNonRootEObjectInListResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.DeleteNonRootEObjectInListResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.ReplaceOrCreateNonRootEObjectSingleResponseResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.ReplaceOrCreateNonRootEObjectSingleResponseResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.DeleteNonRootEObjectSingleResponseResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.DeleteNonRootEObjectSingleResponseResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.UpdateSingleValuedNonContainmentEReferenceResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.UpdateSingleValuedNonContainmentEReferenceResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.InsertEAttributeValueResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.InsertEAttributeValueResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.RemoveEAttributeValueResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.RemoveEAttributeValueResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.InsertNonContainmentEReferenceResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.InsertNonContainmentEReferenceResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.RemoveNonContainmentEReferenceResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.RemoveNonContainmentEReferenceResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.HelperResponseForCreateSecondTestModelResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.HelperResponseForCreateSecondTestModelResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.HelperResponseForDeleteSecondTestModelResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.HelperResponseForDeleteSecondTestModelResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.CreateRootTestResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.CreateRootTestResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.DeleteRootTestResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.DeleteRootTestResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.HelperResponseForNonRootObjectContainerInitializationResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.HelperResponseForNonRootObjectContainerInitializationResponse(userInteracting));
    this.addResponse(mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.HelperResponseForNonRootObjectContainerContentsInitializationResponse.getExpectedChangeType(), new mir.responses.responsesAllElementTypesToAllElementTypes.simpleChangesTests.HelperResponseForNonRootObjectContainerContentsInitializationResponse(userInteracting));
  }
}
