/**
 *
 * $Id$
 */
package tools.vitruv.framework.change.echange.compound.validation;

import org.eclipse.emf.ecore.EObject;

import tools.vitruv.framework.change.echange.eobject.EObjectAddedEChange;
import tools.vitruv.framework.change.echange.eobject.EObjectSubtractedEChange;

import tools.vitruv.framework.change.echange.feature.reference.UpdateReferenceEChange;

/**
 * A sample validator interface for {@link tools.vitruv.framework.change.echange.compound.MoveEObject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MoveEObjectValidator {
	boolean validate();

	boolean validateSubtractWhereChange(UpdateReferenceEChange<EObject> value);
	boolean validateSubtractWhatChange(EObjectSubtractedEChange<EObject> value);
	boolean validateAddWhereChange(UpdateReferenceEChange<EObject> value);
	boolean validateAddWhatChange(EObjectAddedEChange<EObject> value);
}
