/*
 * generated by Xtext 2.9.2
 */
package tools.vitruv.dsls.mirbase.ui.tests;

import com.google.inject.Injector;
import tools.vitruv.dsls.mirbase.ui.internal.MirbaseActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class MirBaseUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MirbaseActivator.getInstance().getInjector("tools.vitruv.dsls.mirbase.MirBase");
	}

}
