package tools.vitruv.applications.familiespersons.persons2families

import mir.reactions.reactionsPersonsToFamilies.personsToFamilies.ChangePropagationSpecificationPersonsToFamilies

class PersonsToFamiliesChangePropagationSpecification extends ChangePropagationSpecificationPersonsToFamilies {

}