package a.b.c;

import static x.y.z.AnotherClass.abc;
import static x.y.z.AnotherClass.*;
import x.y.z.*;
import x.y.z.OtherClass;

public class JavaCompilationUnitTransformationsTest {

}

public class AnyClass extends ExampleClass implements SomeInterface {

	public String testMethod(int firstParam, String secondParam) throws RuntimeException;
	
}

public class ExampleClass {

}