package tools.vitruv.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.system

import tools.vitruv.applications.pcmjava.tests.pojotransformations.pcm2java.system.AssemblyContextMappingTransformationTest

class AssemblyContextMappingGplTransformationTest extends AssemblyContextMappingTransformationTest {
	override protected createChange2CommandTransformingProviding() {
		Change2CommandTransformingProvidingFactory.createPcm2JavaGplImplementationTransformingProviding();
	}
}