/**
 * generated by Xtext 2.10.0
 */
package tools.vitruvius.dsls.response.responseLanguage.impl;

import tools.vitruvius.dsls.response.responseLanguage.AtomicMultiValuedFeatureChange;
import tools.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atomic Multi Valued Feature Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AtomicMultiValuedFeatureChangeImpl extends AtomicFeatureChangeImpl implements AtomicMultiValuedFeatureChange
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtomicMultiValuedFeatureChangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ResponseLanguagePackage.Literals.ATOMIC_MULTI_VALUED_FEATURE_CHANGE;
  }

} //AtomicMultiValuedFeatureChangeImpl
