/**
 * generated by Xtext 2.10.0
 */
package tools.vitruvius.dsls.response.responseLanguage.impl;

import tools.vitruvius.dsls.response.responseLanguage.ModelChange;
import tools.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ModelChangeImpl extends TriggerImpl implements ModelChange
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelChangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ResponseLanguagePackage.Literals.MODEL_CHANGE;
  }

} //ModelChangeImpl
