/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.response.responseLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.response.responseLanguage.AtomicSingleValuedFeatureChange;
import tools.vitruv.dsls.response.responseLanguage.ResponseLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atomic Single Valued Feature Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AtomicSingleValuedFeatureChangeImpl extends AtomicFeatureChangeImpl implements AtomicSingleValuedFeatureChange
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtomicSingleValuedFeatureChangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ResponseLanguagePackage.Literals.ATOMIC_SINGLE_VALUED_FEATURE_CHANGE;
  }

} //AtomicSingleValuedFeatureChangeImpl
