/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.response.responseLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.response.responseLanguage.EffectStatement;
import tools.vitruv.dsls.response.responseLanguage.ResponseLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Effect Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EffectStatementImpl extends TaggableImpl implements EffectStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EffectStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ResponseLanguagePackage.Literals.EFFECT_STATEMENT;
  }

} //EffectStatementImpl
