/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.response.responseLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.response.responseLanguage.InsertRootChange;
import tools.vitruv.dsls.response.responseLanguage.ResponseLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Insert Root Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InsertRootChangeImpl extends AtomicRootObjectChangeImpl implements InsertRootChange
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InsertRootChangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ResponseLanguagePackage.Literals.INSERT_ROOT_CHANGE;
  }

} //InsertRootChangeImpl
