/**
 * generated by Xtext 2.12.0
 */
package tools.vitruv.dsls.mappings.mappingsLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.mappings.mappingsLanguage.EnforceableCondition;
import tools.vitruv.dsls.mappings.mappingsLanguage.MappingsLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Enforceable Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EnforceableConditionImpl extends SingleSidedConditionImpl implements EnforceableCondition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnforceableConditionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MappingsLanguagePackage.Literals.ENFORCEABLE_CONDITION;
  }

} //EnforceableConditionImpl
