/**
 * generated by Xtext 2.12.0
 */
package tools.vitruv.dsls.mappings.mappingsLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.mappings.mappingsLanguage.MappingsLanguagePackage;
import tools.vitruv.dsls.mappings.mappingsLanguage.ValueCondition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Value Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ValueConditionImpl extends EnforceableConditionImpl implements ValueCondition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ValueConditionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MappingsLanguagePackage.Literals.VALUE_CONDITION;
  }

} //ValueConditionImpl
