package tools.vitruv.applications.demo.familiespersons.persons2families

class PersonsToFamiliesChangePropagationSpecification extends mir.reactions.personsToFamilies.PersonsToFamiliesChangePropagationSpecification {

}