/*
 * generated by Xtext
 */
package edu.kit.ipd.sdq.vitruvius.framework.mir.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MIRUiModule extends edu.kit.ipd.sdq.vitruvius.framework.mir.ui.AbstractMIRUiModule {
	public MIRUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
