/*
 * generated by Xtext 2.9.0
 */
package edu.kit.ipd.sdq.vitruvius.dsls.response.validation

import org.eclipse.xtext.validation.Check
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ResponseLanguagePackage
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.Effects
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.UpdatedModel
import static extension edu.kit.ipd.sdq.vitruvius.dsls.response.helper.ResponseLanguageHelper.*;
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.CreatedModel
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ModelChange
import edu.kit.ipd.sdq.vitruvius.dsls.response.responseLanguage.ConcreteModelElementCreate

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class ResponseLanguageValidator extends AbstractResponseLanguageValidator {
	
	@Check
	def checkEffects(Effects effects) {
		if (effects.targetModel instanceof UpdatedModel && effects.codeBlock == null) {
			warning("No code is specified to execute for the models to update.",
				ResponseLanguagePackage.Literals.EFFECTS__CODE_BLOCK);
		}
//		val response = effects.containingResponse;^
//		if (!(response.trigger instanceof ConcreteModelElementCreate) && 
//			effects.targetModel instanceof CreatedModel) {
//			error("A model can only be created in response to the creation of a model element.",
//				ResponseLanguagePackage.Literals.EFFECTS__TARGET_MODEL);
//		}
	}
	
}
