package tools.vitruv.applications.demo.addressesrecipients.transformations

import mir.reactions.adXre_R2L.AdXre_R2LChangePropagationSpecification

class RecipientsToAddressesChangePropagationSpecification extends AdXre_R2LChangePropagationSpecification {
	
}