/*
 * generated by Xtext 2.9.2
 */
package tools.vitruvius.dsls.mirbase.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractMirBaseScopeProvider extends XbaseBatchScopeProvider {
}
