/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.reactions.reactionsLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concrete Model Change</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.reactionsLanguage.ReactionsLanguagePackage#getConcreteModelChange()
 * @model
 * @generated
 */
public interface ConcreteModelChange extends ModelChange
{
} // ConcreteModelChange
