/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.reactions.reactionsLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Insertion In List Change Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.reactionsLanguage.ReactionsLanguagePackage#getElementInsertionInListChangeType()
 * @model
 * @generated
 */
public interface ElementInsertionInListChangeType extends ElementInsertionChangeType, ElementFeatureChangeType
{
} // ElementInsertionInListChangeType
