/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.reactions.reactionsLanguage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invariant Violation Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.reactions.reactionsLanguage.InvariantViolationEvent#getViolation <em>Violation</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.reactions.reactionsLanguage.ReactionsLanguagePackage#getInvariantViolationEvent()
 * @model
 * @generated
 */
public interface InvariantViolationEvent extends Trigger
{
  /**
   * Returns the value of the '<em><b>Violation</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Violation</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Violation</em>' reference.
   * @see #setViolation(EClass)
   * @see tools.vitruv.dsls.reactions.reactionsLanguage.ReactionsLanguagePackage#getInvariantViolationEvent_Violation()
   * @model
   * @generated
   */
  EClass getViolation();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.reactionsLanguage.InvariantViolationEvent#getViolation <em>Violation</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Violation</em>' reference.
   * @see #getViolation()
   * @generated
   */
  void setViolation(EClass value);

} // InvariantViolationEvent
