/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.reactions.reactionsLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Matcher Check Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.reactionsLanguage.ReactionsLanguagePackage#getMatcherCheckStatement()
 * @model
 * @generated
 */
public interface MatcherCheckStatement extends MatcherStatement, CodeBlock
{
} // MatcherCheckStatement
