/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.reactions.reactionsLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Precondition Code Block</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.reactionsLanguage.ReactionsLanguagePackage#getPreconditionCodeBlock()
 * @model
 * @generated
 */
public interface PreconditionCodeBlock extends CodeBlock
{
} // PreconditionCodeBlock
