/**
 * generated by Xtext 2.10.0
 */
package tools.vitruv.dsls.reactions.reactionsLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Routine Call Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.reactionsLanguage.ReactionsLanguagePackage#getRoutineCallStatement()
 * @model
 * @generated
 */
public interface RoutineCallStatement extends RoutineCallBlock, CodeBlock, ActionStatement
{
} // RoutineCallStatement
