/*
 * generated by Xtext 2.9.2
 */
package tools.vitruv.dsls.mapping.scoping;

import tools.vitruv.dsls.mirbase.scoping.MirBaseScopeProvider;

public abstract class AbstractMappingLanguageScopeProvider extends MirBaseScopeProvider {
}
