/*
 * generated by Xtext
 */
package tools.vitruvius.domains.jml.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.autoedit.AbstractEditStrategyProvider;

import tools.vitruvius.domains.jml.language.ui.autoedit.JMLAutoEditStrategyProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JMLUiModule extends tools.vitruvius.domains.jml.language.ui.AbstractJMLUiModule {
    /**
     * Constructor.
     * 
     * @param plugin
     *            The plugin instance.
     */
    public JMLUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }

    @Override
    public Class<? extends AbstractEditStrategyProvider> bindAbstractEditStrategyProvider() {
        return JMLAutoEditStrategyProvider.class;
    }
}
