<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="correspondence" nsURI="http://edu.kit.ipd.sdq.vitruvius/Correspondence/1.0"
    nsPrefix="correspondence">
  <eClassifiers xsi:type="ecore:EClass" name="Correspondences">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondences" upperBound="-1"
        eType="#//Correspondence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelA" lowerBound="1"
        eType="#//Metamodel" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelB" lowerBound="1"
        eType="#//Metamodel" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Correspondence" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependsOn" ordered="false"
        upperBound="-1" eType="#//Correspondence" eOpposite="#//Correspondence/dependedOnBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependedOnBy" ordered="false"
        upperBound="-1" eType="#//Correspondence" eOpposite="#//Correspondence/dependsOn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="M2NCorrespondenceWASSameTypeCorrespondence"
      abstract="true" eSuperTypes="#//Correspondence">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Metaclass for cases where an Object corresponds to another Object of the same metatype (i.e. both objects are either complex-typed EObjects or simple-typed EJavaObjects).&#xA;ElementA and elementB usually point to instances of different metaclasses but their common type T is not a problem as T will never be used more strictly than for the metatype."/>
    </eAnnotations>
    <eOperations name="getAHalfEObjectCorrespondence" eType="#//HalfEObjectCorrespondence"/>
    <eOperations name="getBHalfEObjectCorrespondence" eType="#//HalfEObjectCorrespondence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aHalfCorrespondence" eType="#//HalfTUIDCorrespondence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bHalfCorrespondence" eType="#//HalfTUIDCorrespondence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="One2OneCorrespondenceWASEObjectCorrespondence"
      eSuperTypes="#//M2NCorrespondenceWASSameTypeCorrespondence">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Metaclass for cases where an eObject corresponds to another eObject.&#xA;The correspondence type is indirectly implied by the correspondences of the features of the eObjects."/>
    </eAnnotations>
    <eOperations name="getElementATUID" eType="#//TUID"/>
    <eOperations name="getElementBTUID" eType="#//TUID"/>
    <eOperations name="getA" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eOperations name="getB" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HalfTUIDCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tuids" upperBound="-1"
        eType="#//TUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Metamodel" instanceClassName="edu.kit.ipd.sdq.vitruvius.framework.contracts.datatypes.Metamodel"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TUID" instanceClassName="edu.kit.ipd.sdq.vitruvius.framework.meta.correspondence.datatypes.TUID"/>
  <eClassifiers xsi:type="ecore:EDataType" name="HalfEObjectCorrespondence" instanceClassName="edu.kit.ipd.sdq.vitruvius.framework.meta.correspondence.datatypes.HalfEObjectCorrespondence"
      serializable="false"/>
</ecore:EPackage>
