/**
 * generated by Xtext
 */
package edu.kit.ipd.sdq.vitruvius.framework.design.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.xbase.ui.labeling.XbaseLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class MIRLabelProvider extends XbaseLabelProvider {
  @Inject
  public MIRLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
