/**
 * generated by Xtext 2.12.0
 */
package tools.vitruv.dsls.mappings.mappingsLanguage;

import tools.vitruv.dsls.mirbase.mirBase.MetaclassFeatureReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.mappings.mappingsLanguage.FeatureCondition#getFeature <em>Feature</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.mappings.mappingsLanguage.MappingsLanguagePackage#getFeatureCondition()
 * @model
 * @generated
 */
public interface FeatureCondition extends EnforceableCondition
{
  /**
   * Returns the value of the '<em><b>Feature</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature</em>' containment reference.
   * @see #setFeature(MetaclassFeatureReference)
   * @see tools.vitruv.dsls.mappings.mappingsLanguage.MappingsLanguagePackage#getFeatureCondition_Feature()
   * @model containment="true"
   * @generated
   */
  MetaclassFeatureReference getFeature();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.mappings.mappingsLanguage.FeatureCondition#getFeature <em>Feature</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature</em>' containment reference.
   * @see #getFeature()
   * @generated
   */
  void setFeature(MetaclassFeatureReference value);

} // FeatureCondition
