/**
 * generated by Xtext 2.12.0
 */
package tools.vitruv.dsls.mappings.mappingsLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Num Compare Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.mappings.mappingsLanguage.NumCompareCondition#getOperator <em>Operator</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.mappings.mappingsLanguage.MappingsLanguagePackage#getNumCompareCondition()
 * @model
 * @generated
 */
public interface NumCompareCondition extends SingleValueCondition
{
  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link tools.vitruv.dsls.mappings.mappingsLanguage.NumCompareOperator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operator</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see tools.vitruv.dsls.mappings.mappingsLanguage.NumCompareOperator
   * @see #setOperator(NumCompareOperator)
   * @see tools.vitruv.dsls.mappings.mappingsLanguage.MappingsLanguagePackage#getNumCompareCondition_Operator()
   * @model
   * @generated
   */
  NumCompareOperator getOperator();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.mappings.mappingsLanguage.NumCompareCondition#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see tools.vitruv.dsls.mappings.mappingsLanguage.NumCompareOperator
   * @see #getOperator()
   * @generated
   */
  void setOperator(NumCompareOperator value);

} // NumCompareCondition
