/**
 * generated by Xtext 2.12.0
 */
package tools.vitruv.dsls.mappings.mappingsLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.mappings.mappingsLanguage.MappingsLanguagePackage#getValueCondition()
 * @model
 * @generated
 */
public interface ValueCondition extends EnforceableCondition
{
} // ValueCondition
