/*
 * generated by Xtext 2.9.2
 */
package tools.vitruvius.dsls.mapping.scoping;

import tools.vitruvius.dsls.mirbase.scoping.MirBaseScopeProvider;

public abstract class AbstractMappingLanguageScopeProvider extends MirBaseScopeProvider {
}
