/*
 * generated by Xtext 2.12.0
 */
package tools.vitruv.dsls.mappings.jvmmodel

import tools.vitruv.dsls.reactions.jvmmodel.ReactionsLanguageJvmModelInferrer

/**
 * <p>Infers a JVM model from the source model.</p> 
 *
 * <p>The JVM model should contain all elements that would appear in the Java code 
 * which is generated from the source model. Other models link against the JVM model rather than the source model.</p>     
 */
class MappingsLanguageJvmModelInferrer extends ReactionsLanguageJvmModelInferrer {


}
