package tools.vitruv.applications.pcmjava.tests.pojotransformations.gplimplementation.pcm2java.repository

import tools.vitruv.applications.pcmjava.tests.pojotransformations.pcm2java.repository.RepositoryMappingTransformaitonTest

class RepositoryMappingGplTransformationTest extends RepositoryMappingTransformaitonTest {
	override protected createChange2CommandTransformingProviding() {
		Change2CommandTransformingProvidingFactory.createPcm2JavaGplImplementationTransformingProviding();
	}
}