/*
* generated by Xtext
*/
package edu.kit.ipd.sdq.vitruvius.framework.design;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MIRUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return edu.kit.ipd.sdq.vitruvius.framework.design.ui.internal.MIRActivator.getInstance().getInjector("edu.kit.ipd.sdq.vitruvius.framework.design.MIR");
	}
	
}
